/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-12-14 09:12:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.boardEvent;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class write_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:contains", org.apache.taglibs.standard.functions.Functions.class, "contains", new Class[] {java.lang.String.class, java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/views/boardEvent/../includes/header2.jsp", Long.valueOf(1702513954142L));
    _jspx_dependants.put("jar:file:/D:/javaWork/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/javaWork/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project/WEB-INF/lib/spring-security-taglibs-5.6.0.jar!/META-INF/security.tld", Long.valueOf(1636962998000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.6.0.jar", Long.valueOf(1700468393442L));
    _jspx_dependants.put("/WEB-INF/views/boardEvent/../includes/footer.jsp", Long.valueOf(1702359789364L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1691733144298L));
    _jspx_dependants.put("jar:file:/D:/javaWork/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!---->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>Montana</title>\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<!-- <link rel=\"manifest\" href=\"site.webmanifest\"> -->\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\"\r\n");
      out.write("	href=\"../resources/img/favicon.png\">\r\n");
      out.write("<!-- Place favicon.ico in the root directory -->\r\n");
      out.write("\r\n");
      out.write("<!-- CSS here -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/magnific-popup.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/themify-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/nice-select.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/gijgo.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/animate.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/slicknav.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/style.css\">\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"css/responsive.css\"> -->\r\n");
      out.write("<script src=\"../resources/js/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("@media ( min-width :768px) {\r\n");
      out.write("	#kako-talk-channel-chat-button {\r\n");
      out.write("		position: fixed;\r\n");
      out.write("		z-index: 999;\r\n");
      out.write("		margin: 0 0 0 20px;\r\n");
      out.write("		right: 30px;\r\n");
      out.write("		bottom: 30px;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width :767px) {\r\n");
      out.write("	#kako-talk-channel-chat-button {\r\n");
      out.write("		position: fixed;\r\n");
      out.write("		z-index: 999;\r\n");
      out.write("		margin: 0 0 0 20px;\r\n");
      out.write("		right: 15px;\r\n");
      out.write("		bottom: 30px;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#adminTalk {\r\n");
      out.write("	border-radius: 15px;\r\n");
      out.write("	background-color: #FFC107;\r\n");
      out.write("	border: none;\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!--[if lte IE 9]>\r\n");
      out.write("            <p class=\"browserupgrade\">You are using an <strong>outdated</strong> browser. Please <a href=\"https://browsehappy.com/\">upgrade your browser</a> to improve your experience and security.</p>\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("\r\n");
      out.write("	<!-- header-start -->\r\n");
      out.write("	<header>\r\n");
      out.write("		<div class=\"header-area\"\r\n");
      out.write("			style=\"background-color: rgba(255, 255, 255, 0.5)\">\r\n");
      out.write("			<div id=\"sticky-header\" class=\"main-header-area\">\r\n");
      out.write("				<div class=\"container-fluid p-0\">\r\n");
      out.write("					<div class=\"row align-items-center no-gutters\">\r\n");
      out.write("						<div class=\"col-xl-7 col-lg-7\">\r\n");
      out.write("							<div class=\"main-menu  d-none d-lg-block\">\r\n");
      out.write("								<nav>\r\n");
      out.write("									<ul id=\"navigation\">\r\n");
      out.write("										<li><a href=\"/\"><img\r\n");
      out.write("												src=\"../resources/img/kakao/chunsik.png\" alt=\"\"\r\n");
      out.write("												style=\"width: 60px\"></a></li>\r\n");
      out.write("										<li><a href=\"/\">Home</a></li>\r\n");
      out.write("										 \r\n");
      out.write("										");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("											\r\n");
      out.write("										");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("										\r\n");
      out.write("										<li><a href=\"/flight/search\">Flights<i\r\n");
      out.write("												class=\"ti-angle-down\"></i></a>\r\n");
      out.write("											<ul class=\"submenu\" style=\"width: 220px;\">\r\n");
      out.write("												<li><a href=\"/flight/search\">항공편 검색/예약</a></li>\r\n");
      out.write("												<li><a href=\"/flight/flightDepArrSearch\">출도착 조회</a></li>\r\n");
      out.write("												<li><a href=\"/priceInform\">운임 정책</a></li>\r\n");
      out.write("												<li><a href=\"/memberGrade\">회원 등급 안내</a></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</li>\r\n");
      out.write("										\r\n");
      out.write("										<li><a href=\"/notice/list\">Boards<i class=\"ti-angle-down\"></i></a>\r\n");
      out.write("											<ul class=\"submenu\">\r\n");
      out.write("												<li><a href=\"/notice/list\">공지사항</a></li>\r\n");
      out.write("												<li><a href=\"/qna/list\">Q&A</a></li>\r\n");
      out.write("												<li><a href=\"/boardEvent/list\">이벤트 </a></li>\r\n");
      out.write("												<li><a href=\"/boardDiary/list\">여행일기</a></li>\r\n");
      out.write("												\r\n");
      out.write("											</ul>\r\n");
      out.write("										</li>\r\n");
      out.write("\r\n");
      out.write("										<li><a href=\"/contact\">Contact</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</nav>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- <div class=\"col-xl-2 col-lg-4 \">\r\n");
      out.write("							<div class=\"main-menu  d-none d-lg-block\">\r\n");
      out.write("								<nav>\r\n");
      out.write("									<ul id=\"navigation\">\r\n");
      out.write("										<li><a href=\"/\">Kakao airline</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</nav>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div> -->\r\n");
      out.write("						<div class=\"col-xl-5 col-lg-4 d-none d-lg-block\">\r\n");
      out.write("							<div class=\"book_room\">\r\n");
      out.write("								<div class=\"socail_links\">\r\n");
      out.write("									<ul>\r\n");
      out.write("										<!-- <li><a href=\"/qna/list\">qna \r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li><a href=\"/notice/list\">notice \r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li><a href=\"/boardDiary/list\">Board Diary \r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li><a href=\"/boardEvent/list\">Event </a></li> -->\r\n");
      out.write("										");
      if (_jspx_meth_sec_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("										");
      if (_jspx_meth_sec_005fauthorize_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("									</ul>\r\n");
      out.write("\r\n");
      out.write("								</div>\r\n");
      out.write("								&nbsp;&nbsp;&nbsp;\r\n");
      out.write("								<div id=\"kakao-talk-channel-add-button\"\r\n");
      out.write("									data-channel-public-id=\"_frpnG\" data-size=\"large\"\r\n");
      out.write("									data-support-multiple-densities=\"true\"></div>\r\n");
      out.write("\r\n");
      out.write("								<div id=\"kakao-talk-channel-chat-button\"\r\n");
      out.write("									data-channel-public-id=\"_frpnG\" data-title=\"consult\"\r\n");
      out.write("									data-size=\"small\" data-color=\"yellow\" data-shape=\"pc\"\r\n");
      out.write("									data-support-multiple-densities=\"true\"></div>\r\n");
      out.write("\r\n");
      out.write("								");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("								");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-12\">\r\n");
      out.write("							<div class=\"mobile_menu d-block d-lg-none\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		$(\".logout\").on(\"click\", function(e) {\r\n");
      out.write("	//		e.preventDefault();\r\n");
      out.write("			//alert(\"로그아웃을 진행합니다!\");\r\n");
      out.write("//			$(\"#actionForm\").submit();\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		var link = \"https://center-pf.kakao.com/_frpnG/chats\";\r\n");
      out.write("		$(\"#adminTalk\").on(\"click\", function() {\r\n");
      out.write("			window.open(link);\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"//developers.kakao.com/sdk/js/kakao.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		kakao.init('3156d02ad4070a1c858f024518bda8c5');\r\n");
      out.write("		Kakao.Channel.createAddChannelButton({\r\n");
      out.write("			container : '#kakao-talk-channel-chat-button',\r\n");
      out.write("			channelPublicId : '_frpnG' // 카카오톡 채널 홈 URL에 명시된 id로 설정합니다.\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<!-- 카카오 채널 추가 -->\r\n");
      out.write("	<script>\r\n");
      out.write("		window.kakaoAsyncInit = function() {\r\n");
      out.write("			Kakao.Channel.createAddChannelButton({\r\n");
      out.write("				container : '#kakao-talk-channel-add-button',\r\n");
      out.write("			});\r\n");
      out.write("		};\r\n");
      out.write("\r\n");
      out.write("		(function(d, s, id) {\r\n");
      out.write("			var js, fjs = d.getElementsByTagName(s)[0];\r\n");
      out.write("			if (d.getElementById(id))\r\n");
      out.write("				return;\r\n");
      out.write("			js = d.createElement(s);\r\n");
      out.write("			js.id = id;\r\n");
      out.write("			js.src = 'https://t1.kakaocdn.net/kakao_js_sdk/2.5.0/kakao.channel.min.js';\r\n");
      out.write("			js.integrity = 'sha384-j5TN6EqladB+HIfGV8dVYRIzoJf9Fb4lvrkPmo9KlnDWpN1CZz8yC4rCH1ChRbbh';\r\n");
      out.write("			js.crossOrigin = 'anonymous';\r\n");
      out.write("			fjs.parentNode.insertBefore(js, fjs);\r\n");
      out.write("		})(document, 'script', 'kakao-js-sdk');\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<!-- 카카오 채팅 -->\r\n");
      out.write("	<script>\r\n");
      out.write("		window.kakaoAsyncInit = function() {\r\n");
      out.write("			Kakao.Channel.createChatButton({\r\n");
      out.write("				container : '#kakao-talk-channel-chat-button',\r\n");
      out.write("			});\r\n");
      out.write("		};\r\n");
      out.write("\r\n");
      out.write("		(function(d, s, id) {\r\n");
      out.write("			var js, fjs = d.getElementsByTagName(s)[0];\r\n");
      out.write("			if (d.getElementById(id))\r\n");
      out.write("				return;\r\n");
      out.write("			js = d.createElement(s);\r\n");
      out.write("			js.id = id;\r\n");
      out.write("			js.src = 'https://t1.kakaocdn.net/kakao_js_sdk/2.5.0/kakao.channel.min.js';\r\n");
      out.write("			js.integrity = 'sha384-j5TN6EqladB+HIfGV8dVYRIzoJf9Fb4lvrkPmo9KlnDWpN1CZz8yC4rCH1ChRbbh';\r\n");
      out.write("			js.crossOrigin = 'anonymous';\r\n");
      out.write("			fjs.parentNode.insertBefore(js, fjs);\r\n");
      out.write("			document.getElementsById('aaaaa').classList.toggle('show');\r\n");
      out.write("		})(document, 'script', 'kakao-js-sdk');\r\n");
      out.write("	</script>\r\n");
      out.write("	<!-- header-end -->");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script	src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/summernote/summernote-lite.js\"></script>\r\n");
      out.write("<script src=\"../resources/summernote/summernote-ko-KR.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/summernote/summernote-lite.css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/script/boardEvent.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.jsdelivr.net/jquery/latest/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.jsdelivr.net/momentjs/latest/moment.min.js\"></script> \r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js\"></script> \r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css\" />\r\n");
      out.write("<script>\r\n");
      out.write("	var $jLatest = jQuery.noConflict();\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700\">\r\n");
      out.write("<!-- Google web font \"Open Sans\" -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/font-awesome.min.css\">\r\n");
      out.write("<!-- Font Awesome -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/bootstrap.min.css\">\r\n");
      out.write("<!-- Bootstrap style -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/css/datepicker.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/slick/slick.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/slick/slick-theme.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/templatemo-style.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	.images_container{\r\n");
      out.write("		width: 300px;\r\n");
      out.write("		height: 200px;\r\n");
      out.write("	}\r\n");
      out.write("	.img{\r\n");
      out.write("		width: 300px;\r\n");
      out.write("		height: 200px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.gradient {\r\n");
      out.write("	width: 80px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	font-weight: 900;\r\n");
      out.write("	color: white;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	background: #FFC107;\r\n");
      out.write("	border: solid 2px white;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.container {\r\n");
      out.write("    max-width: 1400px; \r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"margin-top : 180px;\">\r\n");
      out.write("	\r\n");
      out.write("	 <div class=\"p-5 tm-container-outer tm-bg-gray\">\r\n");
      out.write("		<h2>이벤트 등록</h2>\r\n");
      out.write("		<hr class=\"hr1\" noshade>\r\n");
      out.write("		<form action=\"/boardEvent/write\" role=\"form\" method=\"post\" name=\"frm\" >\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"boardTitle\">제목</label> \r\n");
      out.write("				<input type=\"text\" class=\"form-control\" id=\"boardTitle\" name=\"boardTitle\">\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- <input type=\"text\" id=dates name=\"dates\" value=\"\" /> -->\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"boardTitle\">시작일</label> \r\n");
      out.write("				<input type=\"text\" class=\"form-control\" id=\"startDate\" name=\"startDate\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"boardTitle\">종료일</label> \r\n");
      out.write("				<input type=\"text\" class=\"form-control\" id=\"endDate\" name=\"endDate\">\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			주의)파일은 5개까지 업로드 가능하며, 이미지 파일 형식만 사용할 수 있습니다(jpg, jpeg, png, bmp).<br>\r\n");
      out.write("				5MB 이하의 파일만 업로드 하실 수 있습니다.<br>\r\n");
      out.write("				1번 파일이 썸네일에 표시됩니다.\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				1. 파일 지정하기 : <input type=\"file\" multiple=\"multiple\"\r\n");
      out.write("					name=\"uploadFile\" id=\"uploadFile01\" accept=\".png, .jpeg, .jpg, .bmp\"> <br>\r\n");
      out.write("				2. 파일 지정하기 : <input type=\"file\" multiple=\"multiple\"\r\n");
      out.write("					name=\"uploadFile\" id=\"uploadFile02\" accept=\".png, .jpeg, .jpg, .bmp\"> <br>\r\n");
      out.write("				3. 파일 지정하기 : <input type=\"file\" multiple=\"multiple\"\r\n");
      out.write("					name=\"uploadFile\" id=\"uploadFile03\" accept=\".png, .jpeg, .jpg, .bmp\"> <br>\r\n");
      out.write("				4. 파일 지정하기 : <input type=\"file\" multiple=\"multiple\"\r\n");
      out.write("					name=\"uploadFile\" id=\"uploadFile04\" accept=\".png, .jpeg, .jpg, .bmp\"> <br>\r\n");
      out.write("				5. 파일 지정하기 : <input type=\"file\" multiple=\"multiple\"\r\n");
      out.write("					name=\"uploadFile\" id=\"uploadFile05\" accept=\".png, .jpeg, .jpg, .bmp\"> <br>\r\n");
      out.write("			</div>\r\n");
      out.write("		\r\n");
      out.write("			<div class=\"uploadResult\">\r\n");
      out.write("			이미지 미리보기\r\n");
      out.write("				<ul id=\"uploadList\">\r\n");
      out.write("				\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"boardContent\">내용</label><br> \r\n");
      out.write("				<textarea id=\"summernote\" class=\"summernote\" name=\"boardContent\"></textarea>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<br>\r\n");
      out.write("			<div class=\"mt-3 text-right\">\r\n");
      out.write("				<button type=\"button\" class=\"gradient\" onclick=\"location.href='/boardEvent/list'\" style=\"width: 100px\">목록</button>\r\n");
      out.write("				<button type=\"reset\" class=\"gradient\">다시작성</button> &nbsp;\r\n");
      out.write("				<button type=\"submit\" class=\"gradient\" id=\"write\">등록</button> &nbsp;\r\n");
      out.write("			</div>\r\n");
      out.write("			<br>\r\n");
      out.write("			\r\n");
      out.write("			<!-- <div style=\"position: fixed; bottom: 5px; right: 5px;\">\r\n");
      out.write("				<a href=\"#\">\r\n");
      out.write("				<img src=\"img/upArrow.png\" width=\"100px\" height=\"100px\" title=\"위로\">\r\n");
      out.write("				</a><br>\r\n");
      out.write("				<a href=\"#write\">\r\n");
      out.write("				<img src=\"img/downArrow.png\" width=\"100px\" height=\"100px\" title=\"아래로\">\r\n");
      out.write("				</a>\r\n");
      out.write("			</div> -->\r\n");
      out.write("			\r\n");
      out.write("		</form>\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	$('#summernote').summernote({\r\n");
      out.write("		disableDragAndDrop: true,\r\n");
      out.write("		height : 500,\r\n");
      out.write("	/* width : 1200, */\r\n");
      out.write("	lang : \"ko-KR\",\r\n");
      out.write("		toolbar: [\r\n");
      out.write("		    // [groupName, [list of button]]\r\n");
      out.write("		    ['style', ['bold', 'italic', 'underline', 'clear']],\r\n");
      out.write("		    ['fontname', ['fontname']],\r\n");
      out.write("		    ['fontsize', ['fontsize']],\r\n");
      out.write("		    ['color', ['color']],\r\n");
      out.write("		    ['para', ['ul', 'ol', 'paragraph']],\r\n");
      out.write("		    ['height', ['height']],\r\n");
      out.write("		    ['table', ['table']],\r\n");
      out.write("       		['view', ['fullscreen', 'codeview', 'help']]\r\n");
      out.write("		  ]\r\n");
      out.write("		});\r\n");
      out.write("</script> \r\n");
      out.write("	\r\n");
      out.write("<script>\r\n");
      out.write("	$jLatest('input[id=\"dates\"]').daterangepicker();\r\n");
      out.write("	$jLatest('input[id=\"startDate\"]').daterangepicker({\r\n");
      out.write("		singleDatePicker: true,\r\n");
      out.write("	    timePicker: true,\r\n");
      out.write("	    timePicker24Hour: true,\r\n");
      out.write("		 \"locale\": {\r\n");
      out.write("		       \"format\": 'YYYY-MM-DD HH:mm:SS',\r\n");
      out.write("		       \"separator\": \" ~ \",\r\n");
      out.write("		       \"applyLabel\": \"확인\",\r\n");
      out.write("		        \"cancelLabel\": \"취소\",\r\n");
      out.write("		        \"fromLabel\": \"From\",\r\n");
      out.write("		        \"toLabel\": \"To\",\r\n");
      out.write("		        \"customRangeLabel\": \"Custom\",\r\n");
      out.write("		        \"weekLabel\": \"주\",\r\n");
      out.write("		        \"daysOfWeek\": [\r\n");
      out.write("		             \"일\",\r\n");
      out.write("		             \"월\",\r\n");
      out.write("		             \"화\",\r\n");
      out.write("		             \"수\",\r\n");
      out.write("		             \"목\",\r\n");
      out.write("		             \"금\",\r\n");
      out.write("		             \"토\"\r\n");
      out.write("		       ],\r\n");
      out.write("		      \"monthNames\": [\r\n");
      out.write("		             \"1월\",\r\n");
      out.write("		             \"2월\",\r\n");
      out.write("		             \"3월\",\r\n");
      out.write("		             \"4월\",\r\n");
      out.write("		             \"5월\",\r\n");
      out.write("		             \"6월\",\r\n");
      out.write("		             \"7월\",\r\n");
      out.write("		             \"8월\",\r\n");
      out.write("		             \"9월\",\r\n");
      out.write("		             \"10월\",\r\n");
      out.write("		             \"11월\",\r\n");
      out.write("		             \"12월\"\r\n");
      out.write("		        ],\r\n");
      out.write("		        \"firstDay\": 1\r\n");
      out.write("		    },\r\n");
      out.write("	});\r\n");
      out.write("	$jLatest('input[id=\"endDate\"]').daterangepicker({\r\n");
      out.write("		singleDatePicker: true,\r\n");
      out.write("	    timePicker: true,\r\n");
      out.write("	    timePicker24Hour: true,\r\n");
      out.write("		 \"locale\": {\r\n");
      out.write("		       \"format\": 'YYYY-MM-DD HH:mm:SS',\r\n");
      out.write("		       \"separator\": \" ~ \",\r\n");
      out.write("		       \"applyLabel\": \"확인\",\r\n");
      out.write("		        \"cancelLabel\": \"취소\",\r\n");
      out.write("		        \"fromLabel\": \"From\",\r\n");
      out.write("		        \"toLabel\": \"To\",\r\n");
      out.write("		        \"customRangeLabel\": \"Custom\",\r\n");
      out.write("		        \"weekLabel\": \"주\",\r\n");
      out.write("		        \"daysOfWeek\": [\r\n");
      out.write("		             \"일\",\r\n");
      out.write("		             \"월\",\r\n");
      out.write("		             \"화\",\r\n");
      out.write("		             \"수\",\r\n");
      out.write("		             \"목\",\r\n");
      out.write("		             \"금\",\r\n");
      out.write("		             \"토\"\r\n");
      out.write("		       ],\r\n");
      out.write("		      \"monthNames\": [\r\n");
      out.write("		             \"1월\",\r\n");
      out.write("		             \"2월\",\r\n");
      out.write("		             \"3월\",\r\n");
      out.write("		             \"4월\",\r\n");
      out.write("		             \"5월\",\r\n");
      out.write("		             \"6월\",\r\n");
      out.write("		             \"7월\",\r\n");
      out.write("		             \"8월\",\r\n");
      out.write("		             \"9월\",\r\n");
      out.write("		             \"10월\",\r\n");
      out.write("		             \"11월\",\r\n");
      out.write("		             \"12월\"\r\n");
      out.write("		        ],\r\n");
      out.write("		        \"firstDay\": 1\r\n");
      out.write("		    },\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("	\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(e){\r\n");
      out.write("	var formObj = $(\"form[role='form']\");\r\n");
      out.write("	$(\"button[type='submit']\").on(\"click\", function(e){\r\n");
      out.write("//		e.preventDefault();\r\n");
      out.write("		var check = boardCheck();\r\n");
      out.write("		if(check==false){\r\n");
      out.write("			e.preventDefault();\r\n");
      out.write("			console.log(check);\r\n");
      out.write("		} else{	\r\n");
      out.write("			console.log(check);\r\n");
      out.write("			e.preventDefault();\r\n");
      out.write("			console.log(\"submit clicked\");\r\n");
      out.write("			\r\n");
      out.write("			var str=\"\";\r\n");
      out.write("			$(\".uploadResult ul li\").each(function(i, obj){\r\n");
      out.write("				var jobj = $(obj);\r\n");
      out.write("				console.dir(jobj);\r\n");
      out.write("				\r\n");
      out.write("				str+=\"<input type='hidden' name='attachList[\" + i + \"].fileName' value='\" + jobj.data(\"filename\") + \"'>\";\r\n");
      out.write("				str+=\"<input type='hidden' name='attachList[\" + i + \"].uuid' value='\" + jobj.data(\"uuid\") + \"'>\";\r\n");
      out.write("				str+=\"<input type='hidden' name='attachList[\" + i + \"].uploadPath' value='\" + jobj.data(\"path\") + \"'>\";\r\n");
      out.write("				str+=\"<input type='hidden' name='attachList[\" + i + \"].fileType' value='\" + jobj.data(\"type\") + \"'>\";\r\n");
      out.write("				str+=\"<input type='hidden' name='attachList[\" + i + \"].fileOrder' value='\" + jobj.data(\"fileorder\") + \"'>\";\r\n");
      out.write("				str+=\"<input type='hidden' name='attachList[\" + i + \"].fileSize' value='\" + jobj.data(\"filesize\") + \"'>\";\r\n");
      out.write("				str+=\"<input type='hidden' name='attachList[\" + i + \"].repImgYn' value='\" + jobj.data(\"repimgyn\") + \"'>\";\r\n");
      out.write("				\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			formObj.append(str).submit();\r\n");
      out.write("			formObj.unbind('click').click();\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	var regex = new RegExp(\"(.*?)\\.(exe|sh|zip|alz)$\");\r\n");
      out.write("	var maxSize = 5242880; //5MB\r\n");
      out.write("	\r\n");
      out.write("	function checkExtension(filename, fileSize){\r\n");
      out.write("		\r\n");
      out.write("		if(fileSize>=maxSize){\r\n");
      out.write("			alert(\"파일 사이즈를 초과하였습니다\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if(regex.test(filename)){\r\n");
      out.write("			alert(\"해당 종류의 파일은 업로드할 수 없습니다\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		return true;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	$(\"input[type='file']\").focus( function(){\r\n");
      out.write("		  before = $(this).val();	  \r\n");
      out.write("	 	}).change(function(e){\r\n");
      out.write("	 	\r\n");
      out.write("	 		var targetId = $(this).prop(\"id\");\r\n");
      out.write("	 	\r\n");
      out.write("	 	if(before!=''){\r\n");
      out.write("	 		alert(\"아래에서 파일 삭제 후 다시 첨부해주세요\");\r\n");
      out.write("	 		$(\"#\"+targetId).val(\"\");\r\n");
      out.write("	 	}\r\n");
      out.write("	 	else{\r\n");
      out.write("			var formData = new FormData();\r\n");
      out.write("			\r\n");
      out.write("			console.log(\">>>\" + $(this).prop(\"id\"));\r\n");
      out.write("			\r\n");
      out.write("			var inputFile = $(\"#\"+targetId);\r\n");
      out.write("			\r\n");
      out.write("			var files = inputFile[0].files;\r\n");
      out.write("			for(var i=0; i<files.length;i++){\r\n");
      out.write("				if(!checkExtension(files[i].name, files[i].size)){\r\n");
      out.write("					return false;\r\n");
      out.write("				}\r\n");
      out.write("				formData.append(\"uploadFile\", files[i]);\r\n");
      out.write("				formData.append(\"fileOrder\", targetId);\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url: '/uploadAjaxAction',\r\n");
      out.write("				processData: false,\r\n");
      out.write("				contentType: false,\r\n");
      out.write("				data: formData,\r\n");
      out.write("				type: 'POST',\r\n");
      out.write("				dataType: 'json',\r\n");
      out.write("				success: function(result){\r\n");
      out.write("					console.log(result);\r\n");
      out.write("					showUploadResult(result);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("	 	}\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$(\".uploadResult\").on(\"click\", \"button\", function(e){\r\n");
      out.write("		console.log(\"delete file\");\r\n");
      out.write("		\r\n");
      out.write("		var targetFile = $(this).data(\"file\");\r\n");
      out.write("		var type = $(this).data(\"type\");\r\n");
      out.write("		var targetId = $(this).data(\"fileorder\");\r\n");
      out.write("		console.log(\"fileOrder>>\"+targetId);\r\n");
      out.write("		\r\n");
      out.write("		var targetLi = $(this).closest(\"li\");\r\n");
      out.write("		\r\n");
      out.write("		console.log(\"target>>\"+targetFile);\r\n");
      out.write("		console.log(\"type>>>\"+type);\r\n");
      out.write("		\r\n");
      out.write("		$.ajax\r\n");
      out.write("		({\r\n");
      out.write("			url: '/deleteFile',\r\n");
      out.write("			data: {fileName: targetFile, type: type},\r\n");
      out.write("			dataType: 'text',\r\n");
      out.write("			type: 'POST',\r\n");
      out.write("			success: function(result)\r\n");
      out.write("			{\r\n");
      out.write("				alert(\"삭제가 완료되었습니다\");\r\n");
      out.write("				targetLi.remove();\r\n");
      out.write("				$(\"#\"+targetId).val(\"\");\r\n");
      out.write("//				$(\"#\"+targetId).replaceWith($(\"#\"+targetId).clone(true)); //IE에서 동작하지 않으면 사용하기\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("});\r\n");
      out.write("function showUploadResult(uploadResultArr){\r\n");
      out.write("	if(!uploadResultArr||uploadResultArr.length==0){\r\n");
      out.write("		return ;\r\n");
      out.write("	}\r\n");
      out.write("	var uploadUL = $(\".uploadResult ul\");\r\n");
      out.write("	\r\n");
      out.write("	var str=\"\";\r\n");
      out.write("	\r\n");
      out.write("	$(uploadResultArr).each(function(i, obj){\r\n");
      out.write("		//image type\r\n");
      out.write("		if(obj.image){\r\n");
      out.write("			var fileCallPath = encodeURIComponent(obj.uploadPath+\"/s_\"+obj.uuid+\"_\"+obj.fileName);\r\n");
      out.write("			var order = obj.fileOrder.slice(-1);\r\n");
      out.write("			\r\n");
      out.write("			str+= \"<li data-path ='\"+ obj.uploadPath + \"'\";\r\n");
      out.write("			str+=\" data-uuid='\"+ obj.uuid + \"' data-filename='\" + obj.fileName + \"' data-type='\" + obj.image + \"' data-fileOrder='\" + obj.fileOrder + \"' data-fileSize='\" + obj.fileSize + \"' data-repImgYn='\" + obj.repImgYn + \"'\";\r\n");
      out.write("			str+= \" ><div>\";\r\n");
      out.write("			str+=\"<span>\" + order +\"번 파일 : \" + obj.fileName + \"</span>\";\r\n");
      out.write("			str+= \"<button type='button' data-file=\\'\" + fileCallPath+\"\\' data-type='image' data-fileOrder=\" + obj.fileOrder + \" class='btn btn-warning btn-circle'><i class='fa fa-times'></i></button><br>\";\r\n");
      out.write("			str+=\"<img src='/display?fileName=\" + fileCallPath + \"'>\";\r\n");
      out.write("			str+= \"</div>\";\r\n");
      out.write("			str+= \"</li>\";\r\n");
      out.write("		} else{\r\n");
      out.write("			var fileCallPath = encodeURIComponent(obj.uploadPath+\"/\"+obj.uuid+\"_\"+obj.fileName);\r\n");
      out.write("			var fileLink = fileCallPath.replace(new RegExp(/\\\\/g), \"/\");\r\n");
      out.write("			var order = obj.fileOrder.slice(-1);\r\n");
      out.write("			\r\n");
      out.write("			str+=\"<li \";\r\n");
      out.write("			str+= \"data-path='\" + obj.uploadPath +\"' data-uuid='\" + obj.uuid + \"' data-filename='\" + obj.fileName + \"' data-type='\" + obj.image + \"' data-fileOrder='\" + obj.fileOrder + \"' data-fileSize='\" + obj.fileSize + \"' data-repImgYn='\" + obj.repImgYn + \"'\"; \r\n");
      out.write("			str+= \"><div>\";\r\n");
      out.write("			str+=\"<span>\" + order +\"번 파일 : \" + obj.fileName + \"</span>\";\r\n");
      out.write("			str+= \"<button type='button' data-file=\\'\" + fileCallPath+\"\\' data-type='file' class='btn btn-warning btn-circle'><i class='fa fa-times'></i></button><br>\";\r\n");
      out.write("			str+=\"<img src='..resources/upload/noimage.png'></a>\";\r\n");
      out.write("			str+= \"</div>\";\r\n");
      out.write("			str+= \"</li>\";\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	uploadUL.append(str);\r\n");
      out.write("	\r\n");
      out.write("	$(\"#uploadList\").each(function(){\r\n");
      out.write("	    $(this).html($(this).children('li').sort(function(a, b){\r\n");
      out.write("	        return ($(b).data('fileorder')) < ($(a).data('fileorder')) ? 1 : -1;\r\n");
      out.write("	    }));\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<footer class=\"tm-container-outer\">\r\n");
      out.write("	<p class=\"mb-0\">\r\n");
      out.write("		주식회사 카카오에어라인&nbsp;\r\n");
      out.write("		 |&nbsp; 대표 : 플라잉 라이언 &nbsp;|&nbsp; 주소 : 제주특별자치도 제주시 첨단로 242(63309)\r\n");
      out.write("	</p>\r\n");
      out.write("	<p class=\"mb-0\">\r\n");
      out.write("		 사업자등록번호 : 110-81-14794 &nbsp;| &nbsp;통신판매업신고 : 강서 제 16-3010 &nbsp;|&nbsp; 개인정보보호책임자 : 춘식이 카카오에어라인 부사장\r\n");
      out.write("	</p>\r\n");
      out.write("	<p class=\"mb-0\">\r\n");
      out.write("		© 2023-2023 Kakao airline\r\n");
      out.write("	</p>\r\n");
      out.write("\r\n");
      out.write("<!-- 	<p class=\"mb-0\">\r\n");
      out.write("		Copyright © <span class=\"tm-current-year\">2018</span> Your Company .\r\n");
      out.write("		Designed by <a rel=\"nofollow\" href=\"http://www.google.com/+templatemo\"\r\n");
      out.write("			target=\"_parent\">Template Mo</a>\r\n");
      out.write("	</p> -->\r\n");
      out.write("</footer>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- .main-content -->\r\n");
      out.write("\r\n");
      out.write("<!-- load JS files -->\r\n");
      out.write("<script src=\"../resources/js/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("<!-- jQuery (https://jquery.com/download/) -->\r\n");
      out.write("<script src=\"../resources/js/popper.min.js\"></script>\r\n");
      out.write("<!-- https://popper.js.org/ -->\r\n");
      out.write("<script src=\"../resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- https://getbootstrap.com/ -->\r\n");
      out.write("<script src=\"../resources/js/datepicker.min.js\"></script>\r\n");
      out.write("<!-- https://github.com/qodesmith/datepicker -->\r\n");
      out.write("<script src=\"../resources/js/jquery.singlePageNav.min.js\"></script>\r\n");
      out.write("<!-- Single Page Nav (https://github.com/ChrisWojcik/single-page-nav) -->\r\n");
      out.write("<script src=\"../resources/slick/slick.min.js\"></script>\r\n");
      out.write("<!-- http://kenwheeler.github.io/slick/ -->\r\n");
      out.write("<script src=\"../resources/js/jquery.scrollTo.min.js\"></script>\r\n");
      out.write("<!-- https://github.com/flesler/jquery.scrollTo -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- HEADER 부분 스크립트 -->\r\n");
      out.write("<!-- JS here -->\r\n");
      out.write("<script src=\"../resources/js/vendor/modernizr-3.5.0.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/vendor/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/popper.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/isotope.pkgd.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/ajax-form.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/waypoints.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/jquery.counterup.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/imagesloaded.pkgd.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/scrollIt.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/jquery.scrollUp.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/wow.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/nice-select.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/jquery.slicknav.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/plugins.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/gijgo.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--contact js-->\r\n");
      out.write("<script src=\"../resources/js/contact.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/jquery.form.js\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\"></script>\r\n");
      out.write("<script src=\"../resources/js/jquery.validate.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/mail-script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"../resources/js/main.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	$('#datepicker').datepicker({\r\n");
      out.write("		iconsLibrary : 'fontawesome',\r\n");
      out.write("		icons : {\r\n");
      out.write("			rightIcon : '<span class=\"fa fa-caret-down\"></span>'\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	$('#datepicker2').datepicker({\r\n");
      out.write("		iconsLibrary : 'fontawesome',\r\n");
      out.write("		icons : {\r\n");
      out.write("			rightIcon : '<span class=\"fa fa-caret-down\"></span>'\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	/* Google Maps\r\n");
      out.write("	------------------------------------------------*/\r\n");
      out.write("	var map = '';\r\n");
      out.write("	var center;\r\n");
      out.write("\r\n");
      out.write("	function initialize() {\r\n");
      out.write("		var mapOptions = {\r\n");
      out.write("			zoom : 16,\r\n");
      out.write("			center : new google.maps.LatLng(37.769725, -122.462154),\r\n");
      out.write("			scrollwheel : false\r\n");
      out.write("		};\r\n");
      out.write("\r\n");
      out.write("		map = new google.maps.Map(document.getElementById('google-map'),\r\n");
      out.write("				mapOptions);\r\n");
      out.write("\r\n");
      out.write("		google.maps.event.addDomListener(map, 'idle', function() {\r\n");
      out.write("			calculateCenter();\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		google.maps.event.addDomListener(window, 'resize', function() {\r\n");
      out.write("			map.setCenter(center);\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function calculateCenter() {\r\n");
      out.write("		center = map.getCenter();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function loadGoogleMap() {\r\n");
      out.write("		var script = document.createElement('script');\r\n");
      out.write("		script.type = 'text/javascript';\r\n");
      out.write("		script.src = 'https://maps.googleapis.com/maps/api/js?key=AIzaSyDVWt4rJfibfsEDvcuaChUaZRS5NXey1Cs&v=3.exp&sensor=false&'\r\n");
      out.write("				+ 'callback=initialize';\r\n");
      out.write("		document.body.appendChild(script);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/* DOM is ready\r\n");
      out.write("	------------------------------------------------*/\r\n");
      out.write("	$(function() {\r\n");
      out.write("\r\n");
      out.write("		// Change top navbar on scroll\r\n");
      out.write("		$(window).on(\"scroll\", function() {\r\n");
      out.write("			if ($(window).scrollTop() > 100) {\r\n");
      out.write("				$(\".tm-top-bar\").addClass(\"active\");\r\n");
      out.write("			} else {\r\n");
      out.write("				$(\".tm-top-bar\").removeClass(\"active\");\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		// Smooth scroll to search form\r\n");
      out.write("		$('.tm-down-arrow-link').click(function() {\r\n");
      out.write("			$.scrollTo('#tm-section-search', 300, {\r\n");
      out.write("				easing : 'linear'\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		// Date Picker in Search form\r\n");
      out.write("		var pickerCheckIn = datepicker('#inputCheckIn');\r\n");
      out.write("		var pickerCheckOut = datepicker('#inputCheckOut');\r\n");
      out.write("\r\n");
      out.write("		// Update nav links on scroll\r\n");
      out.write("		$('#tm-top-bar').singlePageNav({\r\n");
      out.write("			currentClass : 'active',\r\n");
      out.write("			offset : 60\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		// Close navbar after clicked\r\n");
      out.write("		$('.nav-link').click(function() {\r\n");
      out.write("			$('#mainNav').removeClass('show');\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		// Slick Carousel\r\n");
      out.write("		$('.tm-slideshow').slick({\r\n");
      out.write("			infinite : true,\r\n");
      out.write("			arrows : true,\r\n");
      out.write("			slidesToShow : 1,\r\n");
      out.write("			slidesToScroll : 1\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		loadGoogleMap(); // Google Map                \r\n");
      out.write("		$('.tm-current-year').text(new Date().getFullYear()); // Update year in copyright           \r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/boardEvent/../includes/header2.jsp(89,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.authority[0].getAuthority() == 'ROLE_MEMBER'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("											<li><a href=\"/user\">myPage(user)<i class=\"ti-angle-down\"></i></a>\r\n");
          out.write("\r\n");
          out.write("												<ul class=\"submenu\" style=\"width: 230px;\">\r\n");
          out.write("													<li><a href=\"/user/myPage\">회원정보 조회/수정</a></li>\r\n");
          out.write("													<li><a href=\"/user/mileage\">마일리지 조회</a></li>\r\n");
          out.write("													<li><a href=\"/user/chargePoint\">포인트 충전</a></li>\r\n");
          out.write("\r\n");
          out.write("													<li><a href=\"/user/userResDetail\">구매내역 조회</a></li>\r\n");
          out.write("											</ul></li>\r\n");
          out.write("										");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/boardEvent/../includes/header2.jsp(101,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.authority[0].getAuthority() == 'ROLE_ADMIN'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("										<li>\r\n");
          out.write("											<a href=\"/admin\" style=\"font-size: 15px;\">myPage(admin)<i class=\"ti-angle-down\"></i></a>\r\n");
          out.write("											<ul class=\"submenu\">\r\n");
          out.write("												<li><a href=\"/admin/userInfo\">회원조회</a></li>\r\n");
          out.write("												<li><a href=\"/admin/buyTicket\">항공권 현황</a></li>\r\n");
          out.write("												<li><a href=\"/admin/cancelTicket\">항공권 취소요청</a></li>\r\n");
          out.write("												<li><a href=\"/admin/flightSchedule\">항공스케줄 관리</a></li>\r\n");
          out.write("											</ul>\r\n");
          out.write("										</li>\r\n");
          out.write("										");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f0.setParent(null);
      // /WEB-INF/views/boardEvent/../includes/header2.jsp(158,10) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f0.setAccess("isAnonymous");
      int _jspx_eval_sec_005fauthorize_005f0 = _jspx_th_sec_005fauthorize_005f0.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("											<li><a href=\"/login\" style=\"color: black; font-size: 18px;\"> <strong>login</strong>&nbsp;<!--  <i class=\"fa fa-instagram\"></i>-->\r\n");
        out.write("											</a></li>\r\n");
        out.write("										");
      }
      if (_jspx_th_sec_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f0);
      _jspx_th_sec_005fauthorize_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f1 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f1.setParent(null);
      // /WEB-INF/views/boardEvent/../includes/header2.jsp(162,10) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f1.setAccess("isAuthenticated()");
      int _jspx_eval_sec_005fauthorize_005f1 = _jspx_th_sec_005fauthorize_005f1.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("											");
        if (_jspx_meth_c_005fchoose_005f0(_jspx_th_sec_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\r\n");
        out.write("											");
        out.write("\r\n");
        out.write("											<p>\r\n");
        out.write("												");
        if (_jspx_meth_sec_005fauthentication_005f0(_jspx_th_sec_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("												님 환영합니다!\r\n");
        out.write("												");
        out.write("\r\n");
        out.write("											</p>\r\n");
        out.write("											<form id=\"actionForm\" action=\"/logout\" method=\"post\">\r\n");
        out.write("												<input type=\"hidden\" name=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\"\r\n");
        out.write("													value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\r\n");
        out.write("											</form>\r\n");
        out.write("										");
      }
      if (_jspx_th_sec_005fauthorize_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f1);
      _jspx_th_sec_005fauthorize_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f1);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("												");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("												");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("											");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/boardEvent/../includes/header2.jsp(164,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:contains(loginUser.userId, '@')}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("													<li><a class=\"logout\"\r\n");
          out.write("														href=\"https://kauth.kakao.com/oauth/logout?client_id=607caeca9f2a0089b46f99c667e0dee3&logout_redirect_uri=http://192.168.0.19:8081/logout\">kakaologout</a></li>\r\n");
          out.write("												");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("													<li><a class=\"logout\" href=\"/logout\" style=\"color: black; font-size: 18px;\"><strong>logout</strong></a></li>\r\n");
          out.write("												");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f0 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f1);
      // /WEB-INF/views/boardEvent/../includes/header2.jsp(178,12) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f0.setProperty("principal.username");
      int _jspx_eval_sec_005fauthentication_005f0 = _jspx_th_sec_005fauthentication_005f0.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f0);
      _jspx_th_sec_005fauthentication_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/boardEvent/../includes/header2.jsp(201,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.admin==1 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									<button id=\"adminTalk\">관리자톡 채널</button>\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
