/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-12-15 04:15:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class flightModify_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/javaWork/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/javaWork/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project/WEB-INF/lib/spring-security-taglibs-5.6.0.jar!/META-INF/security.tld", Long.valueOf(1636962998000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.6.0.jar", Long.valueOf(1700468393442L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1691733144298L));
    _jspx_dependants.put("jar:file:/D:/javaWork/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700\">\r\n");
      out.write("<!-- Google web font \"Open Sans\" -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"../resources/font-awesome-4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<!-- Font Awesome -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/bootstrap.min.css\">\r\n");
      out.write("<!-- Bootstrap style -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"../resources/css/datepicker.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"../resources/slick/slick.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"../resources/slick/slick-theme.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/templatemo-style.css\">\r\n");
      out.write("<!-- Templatemo style -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"../resources/js/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(".col-xs-12{\r\n");
      out.write("        width:300px;\r\n");
      out.write("        margin:auto;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"p-5 tm-container-outer tm-bg-gray\" style=\"max-width: 1700px;\">\r\n");
      out.write("<div class=\"container\" style=\"max-width: 1800px;\">\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("		<div class=\"col-xs-12 mx-auto tm-about-text-wrap text-center\">\r\n");
      out.write("			<h2 class=\"text-uppercase mb-4\">운항스케줄 수정</h2>\r\n");
      out.write("			<p class=\"mb-2\">양식에 맞게 정확히 기입 해 주세요.</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("		<div class=\"col-xs-6\">\r\n");
      out.write("			<table class=\"table table-hover\">\r\n");
      out.write("				<thead style=\"background: #ffc107\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>번호</th>\r\n");
      out.write("						<th style=\"width: 10%\">운항기</th>\r\n");
      out.write("						<th>출발지</th>\r\n");
      out.write("						<th>출발공항 코드</th>\r\n");
      out.write("					    <th>출발지역 코드</th>\r\n");
      out.write("						<th>출발시간</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</thead>\r\n");
      out.write("				<tbody>\r\n");
      out.write("					<tr class=\"flight\">\r\n");
      out.write("						<td><input type=\"text\" id=\"fno\" name=\"fno\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.fno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\" style=\"border: 0; background-color: #efefef; width: 40px;\"/></td>\r\n");
      out.write("								<td><input type=\"text\" id=\"flightName\" name=\"flightName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.flightName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\" style=\"border: 0; background-color: #efefef; width: 80px\"/></td>\r\n");
      out.write("								<td><input type=\"text\" id=\"depName\" name=\"depName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.depName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\" style=\"border: 0; background-color: #efefef;width: 80px\"/></td>\r\n");
      out.write("								<td><input type=\"text\" id=\"depCode\" name=\"depCode\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.depCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\" style=\"border: 0; background-color: #efefef;width: 80px;\"/></td>\r\n");
      out.write("								<td><input type=\"text\" id=\"dRCode\" name=\"dRCode\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.depRegionCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\" style=\"border: 0; background-color: #efefef;width: 80px;\"/></td>\r\n");
      out.write("								<td><input type=\"text\" id=\"fullDepTime\" name=\"fullDepTime\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.fullDeptime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required=\"required\" style=\"border: 0; background-color: #efefef;width: 160px\"/></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"col-xs-6\">\r\n");
      out.write("			<table class=\"table table-hover\">\r\n");
      out.write("				<thead style=\"background: #ffc107\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>도착지</th>\r\n");
      out.write("						<th>도착공항 코드</th>\r\n");
      out.write("						<th>도착지역 코드</th>\r\n");
      out.write("						<th>도착시간</th>\r\n");
      out.write("						<th>비행시간</th>\r\n");
      out.write("						<th>수정사유</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</thead>\r\n");
      out.write("				<tbody>\r\n");
      out.write("					<tr class=\"flight\">\r\n");
      out.write("						<td><input type=\"text\" id=\"arrName\" name=\"arrName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.arrName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\" style=\"border: 0; background-color: #efefef;width: 80px\"/></td>\r\n");
      out.write("								<td><input type=\"text\" id=\"aCode\" name=\"aCode\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.arrCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\" style=\"border: 0; background-color: #efefef;width: 80px;\"/></td>\r\n");
      out.write("								<td><input type=\"text\" id=\"aRCode\" name=\"aRCode\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.arrRegionCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\" style=\"border: 0; background-color: #efefef;width: 80px;\"/></td>\r\n");
      out.write("								<td><input type=\"text\" id=\"fullArrTime\" name=\"fullArrTime\" required=\"required\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.fullArrtime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  style=\"border: 0; background-color: #efefef;width: 160px\"/></td>\r\n");
      out.write("								<td><input type=\"text\" id=\"flightTime\" name=\"flightTime\" required=\"required\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.flightTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  style=\"border: 0; background-color: #efefef;width: 80px\"/></td>\r\n");
      out.write("								<td><input type=\"text\" id=\"reason\" name=\"reason\" required=\"required\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.reason}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  style=\"border: 0; background-color: #efefef;width: 80px\"/></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("		<div class=\"col-xs-12\">\r\n");
      out.write("			<button type=\"button\" class=\"btn btn-primary btn-sm btn-custom\"\r\n");
      out.write("				onclick=\"submit()\" style=\"width: 100%\">\r\n");
      out.write("				<i class=\"bi bi-chevron-double-right\"></i>&nbsp;등록\r\n");
      out.write("			</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- .tm-container-outer -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	console.log(\"dddd\");\r\n");
      out.write("	function submit() {\r\n");
      out.write("		alert(\"작동확인..\")\r\n");
      out.write("		check();\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url : \"/admin/flightModify\",\r\n");
      out.write("			type : \"POST\",\r\n");
      out.write("			//dataType : \"json\",\r\n");
      out.write("			async : true,\r\n");
      out.write("			contentType : \"application/json\",\r\n");
      out.write("			data : JSON.stringify({\r\n");
      out.write("				fno : $(\"#fno\").val(),\r\n");
      out.write("				flightName : $(\"#flightName\").val(),\r\n");
      out.write("				depName : $(\"#depName\").val(),\r\n");
      out.write("				depCode : $(\"#depCode\").val(),\r\n");
      out.write("				depRegionCode : $(\"#dRCode\").val(),\r\n");
      out.write("				fullDeptime : $(\"#fullDepTime\").val(),\r\n");
      out.write("				arrName : $(\"#arrName\").val(),\r\n");
      out.write("				arrCode : $(\"#aCode\").val(),\r\n");
      out.write("				arrRegionCode : $(\"#aRCode\").val(),\r\n");
      out.write("				fullArrtime : $(\"#fullArrTime\").val(),\r\n");
      out.write("				flightTime : $(\"#flightTime\").val(),\r\n");
      out.write("				reason : $(\"#reason\").val(),\r\n");
      out.write("				isDelete : 2\r\n");
      out.write("\r\n");
      out.write("			}),\r\n");
      out.write("			success : function(data) {\r\n");
      out.write("				console.log(data);\r\n");
      out.write("				window.close();\r\n");
      out.write("				/* 			location.href=\"admin/flightSchedule\"; */\r\n");
      out.write("			},\r\n");
      out.write("			error : function(err) {\r\n");
      out.write("				console.log(err);\r\n");
      out.write("				/* 			console.log(err.responseText); // 서버에서 전송한 오류 메시지\r\n");
      out.write("				 console.log(err.status);  */\r\n");
      out.write("				alert(\"항공스케줄 수정에 실패했습니다!\");\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("	//유효성 체크\r\n");
      out.write("	function check() {\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
