/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-12-13 08:49:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.join;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:contains", org.apache.taglibs.standard.functions.Functions.class, "contains", new Class[] {java.lang.String.class, java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("jar:file:/D:/javaWork/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/javaWork/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project/WEB-INF/lib/spring-security-taglibs-5.6.0.jar!/META-INF/security.tld", Long.valueOf(1636962998000L));
    _jspx_dependants.put("/WEB-INF/views/join/../includes/footer.jsp", Long.valueOf(1702359789364L));
    _jspx_dependants.put("/WEB-INF/views/join/../includes/header2.jsp", Long.valueOf(1702448849983L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.6.0.jar", Long.valueOf(1700468393442L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1691733144298L));
    _jspx_dependants.put("jar:file:/D:/javaWork/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>Montana</title>\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<!-- <link rel=\"manifest\" href=\"site.webmanifest\"> -->\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\"\r\n");
      out.write("	href=\"../resources/img/favicon.png\">\r\n");
      out.write("<!-- Place favicon.ico in the root directory -->\r\n");
      out.write("\r\n");
      out.write("<!-- CSS here -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/magnific-popup.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/themify-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/nice-select.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/gijgo.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/animate.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/slicknav.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/style.css\">\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"css/responsive.css\"> -->\r\n");
      out.write("<script src=\"../resources/js/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("@media ( min-width :768px) {\r\n");
      out.write("	#kako-talk-channel-chat-button {\r\n");
      out.write("		position: fixed;\r\n");
      out.write("		z-index: 999;\r\n");
      out.write("		margin: 0 0 0 20px;\r\n");
      out.write("		right: 30px;\r\n");
      out.write("		bottom: 30px;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width :767px) {\r\n");
      out.write("	#kako-talk-channel-chat-button {\r\n");
      out.write("		position: fixed;\r\n");
      out.write("		z-index: 999;\r\n");
      out.write("		margin: 0 0 0 20px;\r\n");
      out.write("		right: 15px;\r\n");
      out.write("		bottom: 30px;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#adminTalk {\r\n");
      out.write("	border-radius: 15px;\r\n");
      out.write("	background-color: #FFC107;\r\n");
      out.write("	border: none;\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!--[if lte IE 9]>\r\n");
      out.write("            <p class=\"browserupgrade\">You are using an <strong>outdated</strong> browser. Please <a href=\"https://browsehappy.com/\">upgrade your browser</a> to improve your experience and security.</p>\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("\r\n");
      out.write("	<!-- header-start -->\r\n");
      out.write("	<header>\r\n");
      out.write("		<div class=\"header-area\"\r\n");
      out.write("			style=\"background-color: rgba(255, 255, 255, 0.5)\">\r\n");
      out.write("			<div id=\"sticky-header\" class=\"main-header-area\">\r\n");
      out.write("				<div class=\"container-fluid p-0\">\r\n");
      out.write("					<div class=\"row align-items-center no-gutters\">\r\n");
      out.write("						<div class=\"col-xl-7 col-lg-7\">\r\n");
      out.write("							<div class=\"main-menu  d-none d-lg-block\">\r\n");
      out.write("								<nav>\r\n");
      out.write("									<ul id=\"navigation\">\r\n");
      out.write("										<li><a href=\"/\"><img\r\n");
      out.write("												src=\"../resources/img/kakao/chunsik.png\" alt=\"\"\r\n");
      out.write("												style=\"width: 60px\"></a></li>\r\n");
      out.write("										<li><a href=\"/\">Home</a></li>\r\n");
      out.write("										 \r\n");
      out.write("										");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("											\r\n");
      out.write("										");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("										\r\n");
      out.write("										<li><a href=\"/flight/search\">Flights<i\r\n");
      out.write("												class=\"ti-angle-down\"></i></a>\r\n");
      out.write("											<ul class=\"submenu\" style=\"width: 220px;\">\r\n");
      out.write("												<li><a href=\"/flight/search\">항공편 검색/예약</a></li>\r\n");
      out.write("												<li><a href=\"/flight/flightDepArrSearch\">출도착 조회</a></li>\r\n");
      out.write("												<li><a href=\"/priceInform\">운임 정책</a></li>\r\n");
      out.write("												<li><a href=\"/memberGrade\">회원 등급 안내</a></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</li>\r\n");
      out.write("										\r\n");
      out.write("										<li><a href=\"/notice/list\">Boards<i class=\"ti-angle-down\"></i></a>\r\n");
      out.write("											<ul class=\"submenu\">\r\n");
      out.write("												<li><a href=\"/notice/list\">공지사항</a></li>\r\n");
      out.write("												<li><a href=\"/qna/list\">Q&A</a></li>\r\n");
      out.write("												<li><a href=\"/boardEvent/list\">이벤트 </a></li>\r\n");
      out.write("												<li><a href=\"/boardDiary/list\">여행일기</a></li>\r\n");
      out.write("												\r\n");
      out.write("											</ul>\r\n");
      out.write("										</li>\r\n");
      out.write("\r\n");
      out.write("										<li><a href=\"/contact\">Contact</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</nav>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- <div class=\"col-xl-2 col-lg-4 \">\r\n");
      out.write("							<div class=\"main-menu  d-none d-lg-block\">\r\n");
      out.write("								<nav>\r\n");
      out.write("									<ul id=\"navigation\">\r\n");
      out.write("										<li><a href=\"/\">Kakao airline</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</nav>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div> -->\r\n");
      out.write("						<div class=\"col-xl-5 col-lg-4 d-none d-lg-block\">\r\n");
      out.write("							<div class=\"book_room\">\r\n");
      out.write("								<div class=\"socail_links\">\r\n");
      out.write("									<ul>\r\n");
      out.write("										<!-- <li><a href=\"/qna/list\">qna \r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li><a href=\"/notice/list\">notice \r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li><a href=\"/boardDiary/list\">Board Diary \r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li><a href=\"/boardEvent/list\">Event </a></li> -->\r\n");
      out.write("										");
      if (_jspx_meth_sec_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("										");
      if (_jspx_meth_sec_005fauthorize_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("									</ul>\r\n");
      out.write("\r\n");
      out.write("								</div>\r\n");
      out.write("								&nbsp;&nbsp;&nbsp;\r\n");
      out.write("								<div id=\"kakao-talk-channel-add-button\"\r\n");
      out.write("									data-channel-public-id=\"_frpnG\" data-size=\"large\"\r\n");
      out.write("									data-support-multiple-densities=\"true\"></div>\r\n");
      out.write("\r\n");
      out.write("								<div id=\"kakao-talk-channel-chat-button\"\r\n");
      out.write("									data-channel-public-id=\"_frpnG\" data-title=\"consult\"\r\n");
      out.write("									data-size=\"small\" data-color=\"yellow\" data-shape=\"pc\"\r\n");
      out.write("									data-support-multiple-densities=\"true\"></div>\r\n");
      out.write("\r\n");
      out.write("								");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("								");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-12\">\r\n");
      out.write("							<div class=\"mobile_menu d-block d-lg-none\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		$(\".logout\").on(\"click\", function(e) {\r\n");
      out.write("	//		e.preventDefault();\r\n");
      out.write("			//alert(\"로그아웃을 진행합니다!\");\r\n");
      out.write("//			$(\"#actionForm\").submit();\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		var link = \"https://center-pf.kakao.com/_frpnG/chats\";\r\n");
      out.write("		$(\"#adminTalk\").on(\"click\", function() {\r\n");
      out.write("			window.open(link);\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"//developers.kakao.com/sdk/js/kakao.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		kakao.init('3156d02ad4070a1c858f024518bda8c5');\r\n");
      out.write("		Kakao.Channel.createAddChannelButton({\r\n");
      out.write("			container : '#kakao-talk-channel-chat-button',\r\n");
      out.write("			channelPublicId : '_frpnG' // 카카오톡 채널 홈 URL에 명시된 id로 설정합니다.\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<!-- 카카오 채널 추가 -->\r\n");
      out.write("	<script>\r\n");
      out.write("		window.kakaoAsyncInit = function() {\r\n");
      out.write("			Kakao.Channel.createAddChannelButton({\r\n");
      out.write("				container : '#kakao-talk-channel-add-button',\r\n");
      out.write("			});\r\n");
      out.write("		};\r\n");
      out.write("\r\n");
      out.write("		(function(d, s, id) {\r\n");
      out.write("			var js, fjs = d.getElementsByTagName(s)[0];\r\n");
      out.write("			if (d.getElementById(id))\r\n");
      out.write("				return;\r\n");
      out.write("			js = d.createElement(s);\r\n");
      out.write("			js.id = id;\r\n");
      out.write("			js.src = 'https://t1.kakaocdn.net/kakao_js_sdk/2.5.0/kakao.channel.min.js';\r\n");
      out.write("			js.integrity = 'sha384-j5TN6EqladB+HIfGV8dVYRIzoJf9Fb4lvrkPmo9KlnDWpN1CZz8yC4rCH1ChRbbh';\r\n");
      out.write("			js.crossOrigin = 'anonymous';\r\n");
      out.write("			fjs.parentNode.insertBefore(js, fjs);\r\n");
      out.write("		})(document, 'script', 'kakao-js-sdk');\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<!-- 카카오 채팅 -->\r\n");
      out.write("	<script>\r\n");
      out.write("		window.kakaoAsyncInit = function() {\r\n");
      out.write("			Kakao.Channel.createChatButton({\r\n");
      out.write("				container : '#kakao-talk-channel-chat-button',\r\n");
      out.write("			});\r\n");
      out.write("		};\r\n");
      out.write("\r\n");
      out.write("		(function(d, s, id) {\r\n");
      out.write("			var js, fjs = d.getElementsByTagName(s)[0];\r\n");
      out.write("			if (d.getElementById(id))\r\n");
      out.write("				return;\r\n");
      out.write("			js = d.createElement(s);\r\n");
      out.write("			js.id = id;\r\n");
      out.write("			js.src = 'https://t1.kakaocdn.net/kakao_js_sdk/2.5.0/kakao.channel.min.js';\r\n");
      out.write("			js.integrity = 'sha384-j5TN6EqladB+HIfGV8dVYRIzoJf9Fb4lvrkPmo9KlnDWpN1CZz8yC4rCH1ChRbbh';\r\n");
      out.write("			js.crossOrigin = 'anonymous';\r\n");
      out.write("			fjs.parentNode.insertBefore(js, fjs);\r\n");
      out.write("			document.getElementsById('aaaaa').classList.toggle('show');\r\n");
      out.write("		})(document, 'script', 'kakao-js-sdk');\r\n");
      out.write("	</script>\r\n");
      out.write("	<!-- header-end -->");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700\">\r\n");
      out.write("<!-- Google web font \"Open Sans\" -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"../resources/font-awesome-4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<!-- Font Awesome -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/bootstrap.min.css\">\r\n");
      out.write("<!-- Bootstrap style -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"../resources/css/datepicker.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"../resources/slick/slick.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"../resources/slick/slick-theme.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/templatemo-style.css\">\r\n");
      out.write("<!-- Templatemo style -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"../resources/js/vendor/modernizr.custom.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/normalize.css\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/jquery/latest/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/momentjs/latest/moment.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css\" />\r\n");
      out.write("<script>\r\n");
      out.write("	var $jLatest = jQuery.noConflict();\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	var $jb = jQuery.noConflict();\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- Font Awesome 5 -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css\" />\r\n");
      out.write("<style>\r\n");
      out.write(".id_ok {\r\n");
      out.write("	font-size: small;\r\n");
      out.write("	color: #008000;\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".id_already {\r\n");
      out.write("	font-size: small;\r\n");
      out.write("	color: rgb(201, 0, 0);\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".userNick_ok {\r\n");
      out.write("	font-size: small;\r\n");
      out.write("	color: #008000;\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".userNick_already {\r\n");
      out.write("	font-size: small;\r\n");
      out.write("	color: rgb(201, 0, 0);\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".userPwd_ok {\r\n");
      out.write("	font-size: small;\r\n");
      out.write("	color: #008000;\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".userPwd_already {\r\n");
      out.write("	font-size: small;\r\n");
      out.write("	color: rgb(201, 0, 0);\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body style=\"background: #e6e6e6;\">\r\n");
      out.write("	<div class=\"tm-page-wrap mx-auto\" style=\"margin-top: 180px;\">\r\n");
      out.write("		<section class=\"p-5 tm-container-outer tm-bg-gray\">\r\n");
      out.write("\r\n");
      out.write("			<!-- .tm-container-outer -->\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-xs-12 mx-auto tm-about-text-wrap text-center\">\r\n");
      out.write("					<h2 class=\"text-uppercase mb-4\">회원 정보 입력</h2>\r\n");
      out.write("					<h6>회원님의 개인정보를 입력해주시기 바랍니다.</h6>\r\n");
      out.write("					<br> <br>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<form action=\"/join/memberInfo\" name=\"frm\" method=\"post\"\r\n");
      out.write("				style=\"margin: auto;\">\r\n");
      out.write("				<!-- class=\"tm-contact-form\" -->\r\n");
      out.write("\r\n");
      out.write("				<table\r\n");
      out.write("					style=\"margin: auto; width: 800px; border-top: 0.1px solid rgb(220, 220, 220); border-bottom: 0.1px solid rgb(220, 220, 220);\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<tbody>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th scope=\"row\" style=\"padding: 16px 8px 8px 8px; width: 150px\"><label\r\n");
      out.write("								for=\"userNameK\">한글명<span class=\"icon_require\"\r\n");
      out.write("									style=\"color: red; font-size: x-small;\"> *</span></label></th>\r\n");
      out.write("							<td style=\"padding: 8px\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.userNameK}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th scope=\"row\" style=\"padding: 8px;\"><label for=\"userNameE\">\r\n");
      out.write("									영문명<span class=\"icon_require\"\r\n");
      out.write("									style=\"color: red; font-size: x-small;\"> *</span>\r\n");
      out.write("							</label></th>\r\n");
      out.write("							<td style=\"padding: 8px\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.userNameE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th scope=\"row\" style=\"padding: 8px;\"><label for=\"gender\">성별<span\r\n");
      out.write("									class=\"icon_require\" style=\"color: red; font-size: x-small;\">\r\n");
      out.write("										*</span></label></th>\r\n");
      out.write("							<td style=\"padding: 8px\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.gender}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th scope=\"row\" style=\"padding: 8px;\"><label\r\n");
      out.write("								for=\"userReginumFirst\">생년월일<span class=\"icon_require\"\r\n");
      out.write("									style=\"color: red; font-size: x-small;\"> *</span></label></th>\r\n");
      out.write("							<td style=\"padding: 8px\">\r\n");
      out.write("								");
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.userReginumFirst}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th scope=\"row\" style=\"padding: 8px;\"><label for=\"userId\">아이디\r\n");
      out.write("									<span class=\"icon_require\"\r\n");
      out.write("									style=\"color: red; font-size: x-small;\"> *</span>\r\n");
      out.write("							</label></th>\r\n");
      out.write("							<td style=\"padding: 8px\"><input type=\"text\" id=\"userId\"\r\n");
      out.write("								name=\"userId\" placeholder=\"영문+숫자 6~10자\" title=\"영문+숫자 6~10자\"\r\n");
      out.write("								style=\"width: 200px; display: inline;\" maxlength=\"10\"\r\n");
      out.write("								class=\"input_id; form-control\" oninput=\"return checkId();\"\r\n");
      out.write("								required=\"required\"> <!-- oninput=\"checkId()\"으로 값을 입력할 때마다 바로바로 데이터 확인시킴, style로 색을 지정하고 none;으로 숨겨둔 상태 -->\r\n");
      out.write("								<!-- id ajax 중복체크 --> <span class=\"id_ok\">&nbsp;&nbsp;사용\r\n");
      out.write("									가능한 아이디입니다.</span> <span class=\"id_already\">&nbsp;&nbsp;사용 불가능한\r\n");
      out.write("									아이디입니다.</span>\r\n");
      out.write("\r\n");
      out.write("								<p style=\"color: gray; margin-top: 10px; font-size: 0.8em;\">\r\n");
      out.write("									6 ~ 10자리 영문(대소문자 구별), 숫자 조합 입력 가능 <br>(단 한글, 공백, 특수문자 입력\r\n");
      out.write("									불가) >\r\n");
      out.write("								</p> <!-- 								<button type=\"button\" class=\"btn btn-primary\" id=\"btn_idCheck\"\r\n");
      out.write("									onclick=\"joinInformUseridCheck();\" style=\"display: inline;\">중복확인</button> 아이디 중복 체크 여부\r\n");
      out.write("								<input type=\"hidden\" name=\"idDuplication\" value=\"idUncheck\" />\r\n");
      out.write("								<p style=\"color: gray; margin-top: 10px; font-size: 0.8em;\">\r\n");
      out.write("									6 ~ 10자리 영문(대소문자 구별), 숫자 조합 입력 가능 <br>(단 한글, 공백,\r\n");
      out.write("									특수문자 입력 불가)\r\n");
      out.write("									>\r\n");
      out.write("								</p> --></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th scope=\"row\" style=\"padding: 8px;\"><label for=\"userNick\">닉네임\r\n");
      out.write("									<span class=\"icon_require\"\r\n");
      out.write("									style=\"color: red; font-size: x-small;\"> *</span>\r\n");
      out.write("							</label></th>\r\n");
      out.write("							<td style=\"padding: 8px\"><input type=\"text\" id=\"userNick\"\r\n");
      out.write("								name=\"userNick\" placeholder=\"한글/영문 2~10자\" title=\"한글/영문 2~10자\"\r\n");
      out.write("								style=\"width: 200px; display: inline;\" maxlength=\"10\"\r\n");
      out.write("								class=\"input_Nick; form-control\" oninput=\"return checkNick()\"\r\n");
      out.write("								required=\"required\"> <!-- oninput=\"checkId()\"으로 값을 입력할 때마다 바로바로 데이터 확인시킴, style로 색을 지정하고 none;으로 숨겨둔 상태 -->\r\n");
      out.write("								<!-- id ajax 중복체크 --> <span class=\"userNick_ok\">&nbsp;&nbsp;사용\r\n");
      out.write("									가능한 닉네임입니다.</span> <span class=\"userNick_already\">&nbsp;&nbsp;사용\r\n");
      out.write("									불가능한 닉네임입니다.</span>\r\n");
      out.write("\r\n");
      out.write("								<p style=\"color: gray; margin-top: 10px; font-size: 0.8em;\">\r\n");
      out.write("									2 ~ 10자리 한글, 영문(대소문자 구별), 숫자 조합 입력 가능 <br>(단 공백, 특수문자 입력\r\n");
      out.write("									불가) >\r\n");
      out.write("								</p></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th scope=\"row\" style=\"padding: 8px;\"><label for=\"pwd\">비밀번호<span\r\n");
      out.write("									class=\"icon_require\" style=\"color: red; font-size: x-small;\">\r\n");
      out.write("										*</span></label></th>\r\n");
      out.write("							<td style=\"padding: 8px\"><input type=\"password\" id=\"pwd\"\r\n");
      out.write("								autocomplete=\"off\" name=\"pwd\" placeholder=\"영문+숫자+특수문자 6~10자리\"\r\n");
      out.write("								maxlength=\"10\" title=\"영문+숫자+특수문자 6~10자리\" style=\"width: 200px;\"\r\n");
      out.write("								oninput=\"return checkPwd()\" class=\"form-control\"\r\n");
      out.write("								required=\"required\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th scope=\"row\" style=\"padding: 8px;\"><label for=\"pwd_check\">비밀번호\r\n");
      out.write("									확인<span class=\"icon_require\"\r\n");
      out.write("									style=\"color: red; font-size: x-small;\"> *</span>\r\n");
      out.write("							</label></th>\r\n");
      out.write("							<td style=\"padding: 8px\"><input type=\"password\"\r\n");
      out.write("								id=\"pwd_check\" autocomplete=\"off\"\r\n");
      out.write("								placeholder=\"영문+숫자+특수문자 6~10자리\" title=\"영문+숫자+특수문자 6~10자리\"\r\n");
      out.write("								maxlength=\"10\" style=\"width: 200px; display: inline\"\r\n");
      out.write("								oninput=\"return checkPwd()\" class=\"form-control\"\r\n");
      out.write("								required=\"required\"> <!-- id ajax 중복체크 --> <span\r\n");
      out.write("								class=\"userPwd_ok\">&nbsp;&nbsp;비밀번호 확인이 완료되었습니다.</span> <span\r\n");
      out.write("								class=\"userPwd_already\">&nbsp;&nbsp;비밀번호를 다시 확인해주시기 바랍니다.</span>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("								<!-- <button onclick=\"joinInformPwdCheck()\" id=\"btn_pwdCheck\"\r\n");
      out.write("									type=\"button\" class=\"btn btn-primary\" style=\"display: inline;\">확인</button> <input\r\n");
      out.write("								type=\"hidden\" name=\"pwdDuplication\" value=\"pwdUncheck\" /> -->\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th scope=\"row\" style=\"padding: 8px;\"><label\r\n");
      out.write("								for=\"phone_first\">휴대전화<span class=\"icon_require\"\r\n");
      out.write("									style=\"color: red; font-size: x-small; display: inline;\">\r\n");
      out.write("										*</span></label></th>\r\n");
      out.write("							<td style=\"padding: 8px\" id=\"korea_phone\"><select\r\n");
      out.write("								id=\"phone_first\" name=\"phone_first\"\r\n");
      out.write("								style=\"width: 150px; display: inline;\" title=\"휴대전화 번호 앞자리\"\r\n");
      out.write("								class=\"form-control\" required=\"required\">\r\n");
      out.write("									<option value=\"\">선택</option>\r\n");
      out.write("									<option value=\"010\">010</option>\r\n");
      out.write("									<option value=\"011\">011</option>\r\n");
      out.write("									<option value=\"016\">016</option>\r\n");
      out.write("									<option value=\"017\">017</option>\r\n");
      out.write("									<option value=\"018\">018</option>\r\n");
      out.write("									<option value=\"019\">019</option>\r\n");
      out.write("							</select> <input type=\"text\" id=\"phone_middle\" name=\"phone_middle\"\r\n");
      out.write("								placeholder=\"중간번호\" title=\"휴대전화 번호 가운데 자리\" maxlength=\"4\"\r\n");
      out.write("								style=\"width: 150px; display: inline;\" class=\"form-control\"\r\n");
      out.write("								oninput=\"this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\\..*)\\./g, '$1')\"\r\n");
      out.write("								required=\"required\"> <input type=\"text\" id=\"phone_last\"\r\n");
      out.write("								name=\"phone_last\" placeholder=\"끝 번호\" title=\"휴대전화번호 끝자리\"\r\n");
      out.write("								maxlength=\"4\" style=\"width: 150px; display: inline;\"\r\n");
      out.write("								class=\"form-control\"\r\n");
      out.write("								oninput=\"this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\\..*)\\./g, '$1')\"\r\n");
      out.write("								required=\"required\">\r\n");
      out.write("								<p class=\"txt_error_Msg\" id=\"error_koreaPhone\"\r\n");
      out.write("									style=\"display: none;\"></p></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th scope=\"row\" style=\"padding: 8px;\"><label\r\n");
      out.write("								for=\"input_emailID\">이메일<span class=\"icon_require\"\r\n");
      out.write("									style=\"color: red; font-size: x-small\"> *</span></label></th>\r\n");
      out.write("							<td style=\"padding: 8px\"><input type=\"text\"\r\n");
      out.write("								id=\"input_emailID\" name=\"email\" placeholder=\"이메일 입력\"\r\n");
      out.write("								title=\"이메일 아이디 입력\" style=\"width: 130px; display: inline;\"\r\n");
      out.write("								class=\"form-control\" required=\"required\"> @ &nbsp; <select\r\n");
      out.write("								id=\"select_emailDomain\" title=\"이메일 도메인 선택\" name=\"mail_Domain\"\r\n");
      out.write("								style=\"width: 148px; display: inline;\" onchange=\"display()\"\r\n");
      out.write("								class=\"form-control\" required=\"required\">\r\n");
      out.write("\r\n");
      out.write("									<option value=\"naver.com\" onclick=\"return display()\">naver.com</option>\r\n");
      out.write("\r\n");
      out.write("									<option value=\"hanmail.net\" onclick=\"return display()\">hanmail.net</option>\r\n");
      out.write("\r\n");
      out.write("									<option value=\"gmail.com\" onclick=\"return display()\">gmail.com</option>\r\n");
      out.write("\r\n");
      out.write("									<option value=\"yahoo.co.kr\" onclick=\"return display()\">yahoo.co.kr</option>\r\n");
      out.write("\r\n");
      out.write("									<option value=\"hotmail.com\" onclick=\"return display()\">hotmail.com</option>\r\n");
      out.write("\r\n");
      out.write("									<option value=\"nate.com\" onclick=\"return display()\">nate.com</option>\r\n");
      out.write("\r\n");
      out.write("									<option value=\"yahoo.com\" onclick=\"return display()\">yahoo.com</option>\r\n");
      out.write("\r\n");
      out.write("									<option value=\"hotmail.co.kr\" onclick=\"return display()\">hotmail.co.kr</option>\r\n");
      out.write("\r\n");
      out.write("									<option value=\"\" id=\"option_directInput\"\r\n");
      out.write("										onclick=\"return display()\">직접입력</option>\r\n");
      out.write("							</select> <input type=\"text\" id=\"input_emailDomain\" placeholder=\"직접입력\"\r\n");
      out.write("								name=\"mail_Domain\" title=\"직접입력\"\r\n");
      out.write("								style=\"width: 150px; display: inline;\" disabled=\"disabled\"\r\n");
      out.write("								class=\"form-control\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th scope=\"row\" style=\"padding: 8px;\"><label\r\n");
      out.write("								for=\"input_address\">주소<span class=\"icon_require\"\r\n");
      out.write("									style=\"color: red; font-size: x-small;\"> *</span>\r\n");
      out.write("							</label></th>\r\n");
      out.write("							<td style=\"padding: 8px\" id=\"korea_address\"><input\r\n");
      out.write("								type=\"text\" id=\"sample6_postcode\" name=\"postCode\"\r\n");
      out.write("								placeholder=\"우편번호\" class=\"form-control\"\r\n");
      out.write("								oninput=\"handleOnInput(this, 6); this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\\..*)\\./g, '$1');\"\r\n");
      out.write("								style=\"width: 200px; display: inline;\"> <input\r\n");
      out.write("								type=\"button\" onclick=\"sample6_execDaumPostcode()\"\r\n");
      out.write("								id=\"input_address\" value=\"우편번호 찾기\" class=\"btn btn-primary\"\r\n");
      out.write("								style=\"display: inline;\"><br> <br> <input\r\n");
      out.write("								type=\"text\" name=\"addressDefault\" id=\"sample6_address\"\r\n");
      out.write("								placeholder=\"주소\" class=\"form-control\" style=\"width: 250px\"><br>\r\n");
      out.write("								<input type=\"text\" id=\"sample6_detailAddress\" placeholder=\"상세주소\"\r\n");
      out.write("								class=\"form-control\" name=\"addressDetail\"\r\n");
      out.write("								style=\"display: inline; width: 250px; display: inline;\">\r\n");
      out.write("								<input type=\"text\" id=\"sample6_extraAddress\" placeholder=\"참고항목\"\r\n");
      out.write("								style=\"width: 250px; display: inline;\" class=\"form-control\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("								<p style=\"color: gray; margin-top: 10px; font-size: 0.8em;\">제공해주신\r\n");
      out.write("									주소는 이벤트 또는 우수회원 승급 서비스 제공을 위해 이용됩니다.</p>\r\n");
      out.write("\r\n");
      out.write("								<p class=\"txt_error_Msg\" id=\"error_koreaAddress\"\r\n");
      out.write("									style=\"display: none;\"></p></td>\r\n");
      out.write("							<td id=\"usa_address\" style=\"display: none;\">\r\n");
      out.write("								<p>\r\n");
      out.write("									<input type=\"text\" id=\"input_usDefaultAddress\"\r\n");
      out.write("										placeholder=\"기본 주소\" title=\"기본 주소\" style=\"width: 400px;\">\r\n");
      out.write("									<input type=\"text\" id=\"input_usDetailAddress\"\r\n");
      out.write("										placeholder=\"상세 주소\" title=\"상세 주소\" style=\"width: 400px;\">\r\n");
      out.write("								</p>\r\n");
      out.write("								<p class=\"mar_to15\">\r\n");
      out.write("									<input type=\"text\" id=\"input_usCity\" placeholder=\"도시(City)\"\r\n");
      out.write("										title=\"도시(City)\" style=\"width: 257px;\"> <input\r\n");
      out.write("										type=\"text\" id=\"input_usState\" placeholder=\"주(State)\"\r\n");
      out.write("										title=\"주(State)\" style=\"width: 257px;\"> <input\r\n");
      out.write("										type=\"text\" id=\"input_usZipCode\" placeholder=\"우편번호(Zip Code)\"\r\n");
      out.write("										title=\"우편번호(Zip Code)\" style=\"width: 257px;\">\r\n");
      out.write("								</p>\r\n");
      out.write("								<ul class=\"list_type3 fsz_14 mar_to10\">\r\n");
      out.write("									<li>제공해주신 주소는 이벤트 또는 우수회원 승급 서비스 제공을 위해 이용됩니다.</li>\r\n");
      out.write("\r\n");
      out.write("								</ul>\r\n");
      out.write("								<p class=\"txt_error_Msg\" id=\"error_usAddress\"\r\n");
      out.write("									style=\"display: none;\"></p>\r\n");
      out.write("							</td>\r\n");
      out.write("\r\n");
      out.write("						</tr>\r\n");
      out.write("\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<br> <br>\r\n");
      out.write("				<div align=\"center\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-primary\" id=\"submitButton\"\r\n");
      out.write("						onclick=\"return formCheck()\">확인</button>\r\n");
      out.write("					<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<!-- <input class=\"spinner-border text-warning\" type=\"hidden\"\r\n");
      out.write("									name=\"spinner\" id=\"spinner\"> -->\r\n");
      out.write("				</div>\r\n");
      out.write("				<input type=\"hidden\" name=\"userNameK\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.userNameK}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"userNameE\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.userNameE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"gender\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.gender}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"userReginumFirst\"\r\n");
      out.write("					value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.userReginumFirst}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> <input type=\"hidden\"\r\n");
      out.write("					name=\"userReginumLast\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.userReginumLast}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"termsAgree\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${termsAgree}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("				<input type=\"hidden\" name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("					value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> <br>\r\n");
      out.write("				<br>\r\n");
      out.write("				<br>\r\n");
      out.write("\r\n");
      out.write("			</form>\r\n");
      out.write("\r\n");
      out.write("		</section>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<footer class=\"tm-container-outer\">\r\n");
      out.write("	<p class=\"mb-0\">\r\n");
      out.write("		주식회사 카카오에어라인&nbsp;\r\n");
      out.write("		 |&nbsp; 대표 : 플라잉 라이언 &nbsp;|&nbsp; 주소 : 제주특별자치도 제주시 첨단로 242(63309)\r\n");
      out.write("	</p>\r\n");
      out.write("	<p class=\"mb-0\">\r\n");
      out.write("		 사업자등록번호 : 110-81-14794 &nbsp;| &nbsp;통신판매업신고 : 강서 제 16-3010 &nbsp;|&nbsp; 개인정보보호책임자 : 춘식이 카카오에어라인 부사장\r\n");
      out.write("	</p>\r\n");
      out.write("	<p class=\"mb-0\">\r\n");
      out.write("		© 2023-2023 Kakao airline\r\n");
      out.write("	</p>\r\n");
      out.write("\r\n");
      out.write("<!-- 	<p class=\"mb-0\">\r\n");
      out.write("		Copyright © <span class=\"tm-current-year\">2018</span> Your Company .\r\n");
      out.write("		Designed by <a rel=\"nofollow\" href=\"http://www.google.com/+templatemo\"\r\n");
      out.write("			target=\"_parent\">Template Mo</a>\r\n");
      out.write("	</p> -->\r\n");
      out.write("</footer>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- .main-content -->\r\n");
      out.write("\r\n");
      out.write("<!-- load JS files -->\r\n");
      out.write("<script src=\"../resources/js/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("<!-- jQuery (https://jquery.com/download/) -->\r\n");
      out.write("<script src=\"../resources/js/popper.min.js\"></script>\r\n");
      out.write("<!-- https://popper.js.org/ -->\r\n");
      out.write("<script src=\"../resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- https://getbootstrap.com/ -->\r\n");
      out.write("<script src=\"../resources/js/datepicker.min.js\"></script>\r\n");
      out.write("<!-- https://github.com/qodesmith/datepicker -->\r\n");
      out.write("<script src=\"../resources/js/jquery.singlePageNav.min.js\"></script>\r\n");
      out.write("<!-- Single Page Nav (https://github.com/ChrisWojcik/single-page-nav) -->\r\n");
      out.write("<script src=\"../resources/slick/slick.min.js\"></script>\r\n");
      out.write("<!-- http://kenwheeler.github.io/slick/ -->\r\n");
      out.write("<script src=\"../resources/js/jquery.scrollTo.min.js\"></script>\r\n");
      out.write("<!-- https://github.com/flesler/jquery.scrollTo -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- HEADER 부분 스크립트 -->\r\n");
      out.write("<!-- JS here -->\r\n");
      out.write("<script src=\"../resources/js/vendor/modernizr-3.5.0.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/vendor/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/popper.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/isotope.pkgd.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/ajax-form.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/waypoints.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/jquery.counterup.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/imagesloaded.pkgd.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/scrollIt.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/jquery.scrollUp.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/wow.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/nice-select.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/jquery.slicknav.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/plugins.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/gijgo.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--contact js-->\r\n");
      out.write("<script src=\"../resources/js/contact.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/jquery.form.js\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\"></script>\r\n");
      out.write("<script src=\"../resources/js/jquery.validate.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/mail-script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"../resources/js/main.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	$('#datepicker').datepicker({\r\n");
      out.write("		iconsLibrary : 'fontawesome',\r\n");
      out.write("		icons : {\r\n");
      out.write("			rightIcon : '<span class=\"fa fa-caret-down\"></span>'\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	$('#datepicker2').datepicker({\r\n");
      out.write("		iconsLibrary : 'fontawesome',\r\n");
      out.write("		icons : {\r\n");
      out.write("			rightIcon : '<span class=\"fa fa-caret-down\"></span>'\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	/* Google Maps\r\n");
      out.write("	------------------------------------------------*/\r\n");
      out.write("	var map = '';\r\n");
      out.write("	var center;\r\n");
      out.write("\r\n");
      out.write("	function initialize() {\r\n");
      out.write("		var mapOptions = {\r\n");
      out.write("			zoom : 16,\r\n");
      out.write("			center : new google.maps.LatLng(37.769725, -122.462154),\r\n");
      out.write("			scrollwheel : false\r\n");
      out.write("		};\r\n");
      out.write("\r\n");
      out.write("		map = new google.maps.Map(document.getElementById('google-map'),\r\n");
      out.write("				mapOptions);\r\n");
      out.write("\r\n");
      out.write("		google.maps.event.addDomListener(map, 'idle', function() {\r\n");
      out.write("			calculateCenter();\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		google.maps.event.addDomListener(window, 'resize', function() {\r\n");
      out.write("			map.setCenter(center);\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function calculateCenter() {\r\n");
      out.write("		center = map.getCenter();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function loadGoogleMap() {\r\n");
      out.write("		var script = document.createElement('script');\r\n");
      out.write("		script.type = 'text/javascript';\r\n");
      out.write("		script.src = 'https://maps.googleapis.com/maps/api/js?key=AIzaSyDVWt4rJfibfsEDvcuaChUaZRS5NXey1Cs&v=3.exp&sensor=false&'\r\n");
      out.write("				+ 'callback=initialize';\r\n");
      out.write("		document.body.appendChild(script);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/* DOM is ready\r\n");
      out.write("	------------------------------------------------*/\r\n");
      out.write("	$(function() {\r\n");
      out.write("\r\n");
      out.write("		// Change top navbar on scroll\r\n");
      out.write("		$(window).on(\"scroll\", function() {\r\n");
      out.write("			if ($(window).scrollTop() > 100) {\r\n");
      out.write("				$(\".tm-top-bar\").addClass(\"active\");\r\n");
      out.write("			} else {\r\n");
      out.write("				$(\".tm-top-bar\").removeClass(\"active\");\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		// Smooth scroll to search form\r\n");
      out.write("		$('.tm-down-arrow-link').click(function() {\r\n");
      out.write("			$.scrollTo('#tm-section-search', 300, {\r\n");
      out.write("				easing : 'linear'\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		// Date Picker in Search form\r\n");
      out.write("		var pickerCheckIn = datepicker('#inputCheckIn');\r\n");
      out.write("		var pickerCheckOut = datepicker('#inputCheckOut');\r\n");
      out.write("\r\n");
      out.write("		// Update nav links on scroll\r\n");
      out.write("		$('#tm-top-bar').singlePageNav({\r\n");
      out.write("			currentClass : 'active',\r\n");
      out.write("			offset : 60\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		// Close navbar after clicked\r\n");
      out.write("		$('.nav-link').click(function() {\r\n");
      out.write("			$('#mainNav').removeClass('show');\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		// Slick Carousel\r\n");
      out.write("		$('.tm-slideshow').slick({\r\n");
      out.write("			infinite : true,\r\n");
      out.write("			arrows : true,\r\n");
      out.write("			slidesToShow : 1,\r\n");
      out.write("			slidesToScroll : 1\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		loadGoogleMap(); // Google Map                \r\n");
      out.write("		$('.tm-current-year').text(new Date().getFullYear()); // Update year in copyright           \r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function handleOnInput(el, maxlength) {\r\n");
      out.write("			if (el.value.length > maxlength) {\r\n");
      out.write("				el.value = el.value.substr(0, maxlength);\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function checkId() {\r\n");
      out.write("			var userId = $('#userId').val();\r\n");
      out.write("			var checkIdResult = \"\";\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : '/join/userIdDuplicateCheck', //controller에서 요청받을 주소\r\n");
      out.write("				type : 'post', //post방식으로 전달\r\n");
      out.write("				data : {\r\n");
      out.write("					userId : userId\r\n");
      out.write("				}, //데이터\r\n");
      out.write("				dataType : 'json',\r\n");
      out.write("				async : false,\r\n");
      out.write("				success : function(userIdCnt) { //controller에서 넘어온 cnt값을 받음\r\n");
      out.write("					if (userIdCnt == 0) { //0이면 사용가능 1이면 중복\r\n");
      out.write("						$('.id_ok').css(\"display\", \"inline-block\");\r\n");
      out.write("						$('.id_already').css(\"display\", \"none\");\r\n");
      out.write("						checkIdResult = true;\r\n");
      out.write("					} else { //!=0일때 (중복일때)\r\n");
      out.write("						$('.id_ok').css(\"display\", \"none\");\r\n");
      out.write("						$('.id_already').css(\"display\", \"inline-block\");\r\n");
      out.write("						checkIdResult = false;\r\n");
      out.write("						//$('#userId').val(''); 값을 지우는데 지우면 확인못할것같아서 주석처리함\r\n");
      out.write("					}\r\n");
      out.write("				},\r\n");
      out.write("				error : function() {\r\n");
      out.write("					alert(\"오류가 발생하였습니다.\");\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("			return checkIdResult;\r\n");
      out.write("		};\r\n");
      out.write("\r\n");
      out.write("		function checkNick() {\r\n");
      out.write("			var userNick = $('#userNick').val();\r\n");
      out.write("			var checkNickResult = \"\";\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : '/join/userNickDuplicateCheck', //controller에서 요청받을 주소\r\n");
      out.write("				type : 'post', //post방식으로 전달\r\n");
      out.write("				data : {\r\n");
      out.write("					userNick : userNick\r\n");
      out.write("				}, //데이터\r\n");
      out.write("				dataType : 'json',\r\n");
      out.write("				async : false,\r\n");
      out.write("				success : function(userNickCnt) { //controller에서 넘어온 cnt값을 받음\r\n");
      out.write("					if (userNickCnt == 0) { //0이면 사용가능 1이면 중복\r\n");
      out.write("						$('.userNick_ok').css(\"display\", \"inline-block\");\r\n");
      out.write("						$('.userNick_already').css(\"display\", \"none\");\r\n");
      out.write("						checkNickResult = true;\r\n");
      out.write("					} else { //!=0일때 (중복일때)\r\n");
      out.write("						$('.userNick_ok').css(\"display\", \"none\");\r\n");
      out.write("						$('.userNick_already').css(\"display\", \"inline-block\");\r\n");
      out.write("						//$('#userNick').val(''); 값을 지우는데 지우면 확인못할것같아서 주석처리함\r\n");
      out.write("						checkNickResult = false;\r\n");
      out.write("					}\r\n");
      out.write("				},\r\n");
      out.write("				error : function() {\r\n");
      out.write("					alert(\"오류가 발생하였습니다.\");\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("			return checkNickResult;\r\n");
      out.write("		};\r\n");
      out.write("\r\n");
      out.write("		function checkPwd() {\r\n");
      out.write("			var pwd = $('#pwd').val();\r\n");
      out.write("			var pwd_check = $('#pwd_check').val();\r\n");
      out.write("			var checkPwdResult = \"\";\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : '/join/userPwdCheck', //controller에서 요청받을 주소\r\n");
      out.write("				type : 'post', //post방식으로 전달\r\n");
      out.write("				data : {\r\n");
      out.write("					pwd : pwd,\r\n");
      out.write("					pwd_check : pwd_check\r\n");
      out.write("				}, //데이터\r\n");
      out.write("				dataType : 'json',\r\n");
      out.write("				async : false,\r\n");
      out.write("				success : function(userPwdCnt) { //controller에서 넘어온 cnt값을 받음\r\n");
      out.write("					if (userPwdCnt == 1) { //1이면 일치(확인됨)\r\n");
      out.write("						$('.userPwd_ok').css(\"display\", \"inline-block\");\r\n");
      out.write("						$('.userPwd_already').css(\"display\", \"none\");\r\n");
      out.write("						checkPwdResult = true;\r\n");
      out.write("					} else if (userPwdCnt == 0) { // 0 불일치\r\n");
      out.write("						$('.userPwd_ok').css(\"display\", \"none\");\r\n");
      out.write("						$('.userPwd_already').css(\"display\", \"inline-block\");\r\n");
      out.write("						//값을 지우면 확인못할것같아서 주석처리함\r\n");
      out.write("						checkPwdResult = false;\r\n");
      out.write("					} else { //-1 : controller에서 문제가 발생\r\n");
      out.write("						alert(\"오류가 발생하였습니다.\");\r\n");
      out.write("					}\r\n");
      out.write("				},\r\n");
      out.write("				error : function() {\r\n");
      out.write("					alert(\"오류가 발생하였습니다.\");\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("			return checkPwdResult;\r\n");
      out.write("		};\r\n");
      out.write("\r\n");
      out.write("		function formCheck() {\r\n");
      out.write("			/*  if (document.frm.idDuplication.value == \"idUncheck\" ) {\r\n");
      out.write("			    alert(\"아이디 중복확인을 해주세요.\");\r\n");
      out.write("			    document.frm.userid.focus;\r\n");
      out.write("			    return false;\r\n");
      out.write("			 }\r\n");
      out.write("			 else if (document.frm.pwdDuplication.value == \"pwdUncheck\" ) {\r\n");
      out.write("			    alert(\"비밀번호를 다시 확인해주세요.\");\r\n");
      out.write("			    document.frm.pwd.focus;\r\n");
      out.write("			    return false;\r\n");
      out.write("			 }  */\r\n");
      out.write("			var regId = /^[a-zA-Z0-9]{6,10}$/;\r\n");
      out.write("			var regIdPw = /^(?=.*[a-zA-Z])(?=.*[!@#$%^*+=-])(?=.*[0-9]).{6,10}$/;\r\n");
      out.write("			var regNick = /^[a-zA-Z0-9가-힣]{2,10}$/;\r\n");
      out.write("			var form = document.frm;\r\n");
      out.write("			var submitButton = document.getElementById('submitButton');\r\n");
      out.write("			var spinner = document.getElementById('spinner');\r\n");
      out.write("\r\n");
      out.write("			if (document.frm.userId.value.length == 0) {\r\n");
      out.write("				alert(\"아이디를 입력해주세요.\");\r\n");
      out.write("				document.frm.userId.focus;\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (!regId.test(document.frm.userId.value)) { //아이디 영어 대소문자 확인\r\n");
      out.write("				alert(\"6~10자 영문 대소문자, 숫자만 입력해주세요.\")\r\n");
      out.write("				userId.focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (!checkId()) {\r\n");
      out.write("				alert(\"아이디를 다시 확인해주세요.\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			//닉네임\r\n");
      out.write("			else if (document.frm.userNick.value.length == 0) {\r\n");
      out.write("				alert(\"닉네임을 입력해주세요.\")\r\n");
      out.write("				document.frm.userNick.focus;\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (!regNick.test(document.frm.userNick.value)) {\r\n");
      out.write("				alert(\"2~10자리 한글, 영문(대소문자 구별), 숫자를 입력해주세요.\")\r\n");
      out.write("				document.frm.userNick.focus;\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (!checkNick()) {\r\n");
      out.write("				alert(\"닉네임을 다시 확인해주세요.\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			//비밀번호 확인\r\n");
      out.write("			else if (document.frm.pwd.value.length == 0) {\r\n");
      out.write("				alert(\"비밀번호를 입력하세요.\")\r\n");
      out.write("				pwd.focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (!regIdPw.test(document.frm.pwd.value)) {\r\n");
      out.write("				alert(\"6~10자 영문 대소문자, 숫자, 특수문자를 입력해주세요.\")\r\n");
      out.write("				pwd.focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (document.frm.pwd.value == document.frm.userId.value) {\r\n");
      out.write("				alert(\"아이디와 동일한 비밀번호를 사용할 수 없습니다.\")\r\n");
      out.write("				pwd.focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (!checkPwd()) {\r\n");
      out.write("				alert(\"비밀번호를 다시 확인해주세요.\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			else if (document.frm.phone_first.value.length == 0) {\r\n");
      out.write("				alert(\"휴대전화번호를 다시 확인해주세요.\")\r\n");
      out.write("				document.frm.phone_first.focus;\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (document.frm.phone_middle.value.length == 0\r\n");
      out.write("					|| document.frm.phone_middle.value.length < 4) {\r\n");
      out.write("				alert(\"휴대전화번호 가운데 자리를 다시 확인해주세요(4글자).\")\r\n");
      out.write("				document.frm.phone_middle.focus;\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (document.frm.phone_last.value.length == 0\r\n");
      out.write("					|| document.frm.phone_last.value.length < 4) {\r\n");
      out.write("				alert(\"휴대전화번호 마지막 자리를 다시 확인해주세요(4글자).\")\r\n");
      out.write("				document.frm.phone_last.focus;\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			else if (document.frm.email.value.length == 0) {\r\n");
      out.write("				alert(\"이메일을 다시 확인해주세요.\")\r\n");
      out.write("				document.frm.email.focus;\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (document.frm.email.value.includes('@')) {\r\n");
      out.write("				alert(\"이메일을 다시 확인해주세요.\")\r\n");
      out.write("				document.frm.email.focus;\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (document.frm.postCode.value.length == 0) {\r\n");
      out.write("				alert(\"우편번호를 다시 확인해주세요.\")\r\n");
      out.write("				document.frm.postCode.focus;\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (document.frm.addressDefault.value.length == 0) {\r\n");
      out.write("				alert(\"주소를 다시 확인해주세요.\")\r\n");
      out.write("				document.frm.addressDefault.focus;\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			//disabled=\"disabled\"\r\n");
      out.write("			submitButton.disabled = 'disable';\r\n");
      out.write("			//spinner.type = 'text';\r\n");
      out.write("\r\n");
      out.write("			form.submit();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		//직접입력란.. 직접입력 선택해야만 직접입력input보이게....\r\n");
      out.write("		function display() {\r\n");
      out.write("			var select = document.getElementById(\"select_emailDomain\");\r\n");
      out.write("			var option_directInput = document\r\n");
      out.write("					.getElementById(\"option_directInput\");\r\n");
      out.write("			var input_emailDomain = document\r\n");
      out.write("					.getElementById(\"input_emailDomain\");\r\n");
      out.write("\r\n");
      out.write("			if (select.value === \"\") {\r\n");
      out.write("				input_emailDomain.disabled = false;\r\n");
      out.write("			} else {\r\n");
      out.write("				input_emailDomain.disabled = true;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		function sample6_execDaumPostcode() {\r\n");
      out.write("			new daum.Postcode(\r\n");
      out.write("					{\r\n");
      out.write("						oncomplete : function(data) {\r\n");
      out.write("							// 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("							// 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("							// 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("							var addr = ''; // 주소 변수\r\n");
      out.write("							var extraAddr = ''; // 참고항목 변수\r\n");
      out.write("\r\n");
      out.write("							//사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("							if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("								addr = data.roadAddress;\r\n");
      out.write("							} else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("								addr = data.jibunAddress;\r\n");
      out.write("							}\r\n");
      out.write("\r\n");
      out.write("							// 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.\r\n");
      out.write("							if (data.userSelectedType === 'R') {\r\n");
      out.write("								// 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("								// 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("								if (data.bname !== ''\r\n");
      out.write("										&& /[동|로|가]$/g.test(data.bname)) {\r\n");
      out.write("									extraAddr += data.bname;\r\n");
      out.write("								}\r\n");
      out.write("								// 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("								if (data.buildingName !== ''\r\n");
      out.write("										&& data.apartment === 'Y') {\r\n");
      out.write("									extraAddr += (extraAddr !== '' ? ', '\r\n");
      out.write("											+ data.buildingName\r\n");
      out.write("											: data.buildingName);\r\n");
      out.write("								}\r\n");
      out.write("								// 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("								if (extraAddr !== '') {\r\n");
      out.write("									extraAddr = ' (' + extraAddr + ')';\r\n");
      out.write("								}\r\n");
      out.write("								// 조합된 참고항목을 해당 필드에 넣는다.\r\n");
      out.write("								document.getElementById(\"sample6_extraAddress\").value = extraAddr;\r\n");
      out.write("\r\n");
      out.write("							} else {\r\n");
      out.write("								document.getElementById(\"sample6_extraAddress\").value = '';\r\n");
      out.write("							}\r\n");
      out.write("\r\n");
      out.write("							// 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("							document.getElementById('sample6_postcode').value = data.zonecode;\r\n");
      out.write("							document.getElementById(\"sample6_address\").value = addr;\r\n");
      out.write("							// 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("							document.getElementById(\"sample6_detailAddress\")\r\n");
      out.write("									.focus();\r\n");
      out.write("						}\r\n");
      out.write("					}).open();\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/join/../includes/header2.jsp(89,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.authority[0].getAuthority() == 'ROLE_MEMBER'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("											<li><a href=\"/user\">myPage(user)<i class=\"ti-angle-down\"></i></a>\r\n");
          out.write("\r\n");
          out.write("												<ul class=\"submenu\" style=\"width: 230px;\">\r\n");
          out.write("													<li><a href=\"/user/myPage\">회원정보 조회/수정</a></li>\r\n");
          out.write("													<li><a href=\"/user/mileage\">마일리지 조회</a></li>\r\n");
          out.write("													<li><a href=\"/user/chargePoint\">포인트 충전</a></li>\r\n");
          out.write("\r\n");
          out.write("													<li><a href=\"/user/userResDetail\">구매내역 조회</a></li>\r\n");
          out.write("											</ul></li>\r\n");
          out.write("										");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/join/../includes/header2.jsp(101,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.authority[0].getAuthority() == 'ROLE_ADMIN'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("										<li>\r\n");
          out.write("											<a href=\"/admin\" style=\"font-size: 15px;\">myPage(admin)<i class=\"ti-angle-down\"></i></a>\r\n");
          out.write("											<ul class=\"submenu\">\r\n");
          out.write("												<li><a href=\"/admin/userInfo\">회원조회</a></li>\r\n");
          out.write("												<li><a href=\"/admin/buyTicket\">항공권 현황</a></li>\r\n");
          out.write("												<li><a href=\"/admin/cancelTicket\">항공권 취소요청</a></li>\r\n");
          out.write("												<li><a href=\"/admin/flightSchedule\">항공스케줄 관리</a></li>\r\n");
          out.write("											</ul>\r\n");
          out.write("										</li>\r\n");
          out.write("										");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f0.setParent(null);
      // /WEB-INF/views/join/../includes/header2.jsp(158,10) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f0.setAccess("isAnonymous");
      int _jspx_eval_sec_005fauthorize_005f0 = _jspx_th_sec_005fauthorize_005f0.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("											<li><a href=\"/login\" style=\"color: black; font-size: 18px;\"> <strong>login</strong>&nbsp;<!--  <i class=\"fa fa-instagram\"></i>-->\r\n");
        out.write("											</a></li>\r\n");
        out.write("										");
      }
      if (_jspx_th_sec_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f0);
      _jspx_th_sec_005fauthorize_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f1 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f1.setParent(null);
      // /WEB-INF/views/join/../includes/header2.jsp(162,10) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f1.setAccess("isAuthenticated()");
      int _jspx_eval_sec_005fauthorize_005f1 = _jspx_th_sec_005fauthorize_005f1.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("											");
        if (_jspx_meth_c_005fchoose_005f0(_jspx_th_sec_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\r\n");
        out.write("											");
        out.write("\r\n");
        out.write("											<p>\r\n");
        out.write("												");
        if (_jspx_meth_sec_005fauthentication_005f0(_jspx_th_sec_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("												님 환영합니다!\r\n");
        out.write("												");
        out.write("\r\n");
        out.write("											</p>\r\n");
        out.write("											<form id=\"actionForm\" action=\"/logout\" method=\"post\">\r\n");
        out.write("												<input type=\"hidden\" name=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\"\r\n");
        out.write("													value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\r\n");
        out.write("											</form>\r\n");
        out.write("										");
      }
      if (_jspx_th_sec_005fauthorize_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f1);
      _jspx_th_sec_005fauthorize_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f1);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("												");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("												");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("											");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/join/../includes/header2.jsp(164,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:contains(loginUser.userId, '@')}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("													<li><a class=\"logout\"\r\n");
          out.write("														href=\"https://kauth.kakao.com/oauth/logout?client_id=607caeca9f2a0089b46f99c667e0dee3&logout_redirect_uri=http://localhost:8081/logout\">kakaologout</a></li>\r\n");
          out.write("												");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("													<li><a class=\"logout\" href=\"/logout\" style=\"color: black; font-size: 18px;\"><strong>logout</strong></a></li>\r\n");
          out.write("												");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f0 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f1);
      // /WEB-INF/views/join/../includes/header2.jsp(178,12) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f0.setProperty("principal.username");
      int _jspx_eval_sec_005fauthentication_005f0 = _jspx_th_sec_005fauthentication_005f0.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f0);
      _jspx_th_sec_005fauthentication_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/join/../includes/header2.jsp(201,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.admin==1 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									<button id=\"adminTalk\">관리자톡 채널</button>\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
